-- Generated by scripts/generate-seed-sql.mjs. Do not edit by hand.
-- Re-run `make db-seed` after changing JSON source data.

BEGIN;
INSERT INTO countries (code, name, language_code, market_notes, source_data, updated_at)
VALUES (
  'de',
  'Deutschland',
  'de',
  'German pilot market',
  '{"country":"DE","language":"de","currency":"EUR","designVariant":"technical_touring","marketGroup":"premium_touring","defaultSolutionOrder":["diagnose_problem","reversible_addon","oem_comfort_seat","aftermarket_seat","professional_upholsterer","diy"],"cookieMode":"minimal_bottom_bar","premiumAftermarketVisibility":"high","localRepairVisibility":"medium"}'::jsonb,
  now()
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  language_code = EXCLUDED.language_code,
  market_notes = EXCLUDED.market_notes,
  source_data = EXCLUDED.source_data,
  updated_at = now();
INSERT INTO motorcycles (
    slug, brand, model, segment, country_priority, status, guide_path,
    seat_pain_focus, why_next, source_data, updated_at
  )
  VALUES (
    'suzuki-gsx-s1000gx',
    'Suzuki',
    'Suzuki GSX-S1000GX',
    'Sport-Tourer / Crossover',
    'Deutschland MVP',
    'active',
    '/de/motorrad-sitzbank/suzuki-gsx-s1000gx/',
    'Druck nach 45 bis 90 Minuten, Hitze, Sitzwinkel, Touring-Komfort',
    'Dein zuletzt bearbeitetes Motorrad und aktueller Referenz-Guide.',
    '{"name":"Suzuki GSX-S1000GX","brand":"Suzuki","segment":"Sport-Tourer / Crossover","countryPriority":"Deutschland MVP","status":"active","path":"/de/motorrad-sitzbank/suzuki-gsx-s1000gx/","seatPainFocus":"Druck nach 45 bis 90 Minuten, Hitze, Sitzwinkel, Touring-Komfort","whyNext":"Dein zuletzt bearbeitetes Motorrad und aktueller Referenz-Guide.","slug":"suzuki-gsx-s1000gx"}'::jsonb,
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    segment = EXCLUDED.segment,
    country_priority = EXCLUDED.country_priority,
    status = EXCLUDED.status,
    guide_path = EXCLUDED.guide_path,
    seat_pain_focus = EXCLUDED.seat_pain_focus,
    why_next = EXCLUDED.why_next,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycles (
    slug, brand, model, segment, country_priority, status, guide_path,
    seat_pain_focus, why_next, source_data, updated_at
  )
  VALUES (
    'bmw-r-1300-gs',
    'BMW',
    'BMW R 1300 GS',
    'Adventure Touring',
    'Deutschland / DACH',
    'planned',
    NULL,
    'Langstrecke, hohe Sitzbank, Sozius, Zubehörvielfalt',
    'Sehr verbreitete Reisemaschine mit vielen Sitzbankoptionen.',
    '{"name":"BMW R 1300 GS","brand":"BMW","segment":"Adventure Touring","countryPriority":"Deutschland / DACH","status":"planned","path":"","seatPainFocus":"Langstrecke, hohe Sitzbank, Sozius, Zubehörvielfalt","whyNext":"Sehr verbreitete Reisemaschine mit vielen Sitzbankoptionen.","slug":"bmw-r-1300-gs"}'::jsonb,
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    segment = EXCLUDED.segment,
    country_priority = EXCLUDED.country_priority,
    status = EXCLUDED.status,
    guide_path = EXCLUDED.guide_path,
    seat_pain_focus = EXCLUDED.seat_pain_focus,
    why_next = EXCLUDED.why_next,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycles (
    slug, brand, model, segment, country_priority, status, guide_path,
    seat_pain_focus, why_next, source_data, updated_at
  )
  VALUES (
    'bmw-r-1250-gs',
    'BMW',
    'BMW R 1250 GS',
    'Adventure Touring',
    'Deutschland / DACH gebraucht',
    'planned',
    NULL,
    'Touring, niedrige/hohe Sitzbank, Komfortsitz, Sattlerumbau',
    'Großer Bestand und viele Erfahrungsberichte.',
    '{"name":"BMW R 1250 GS","brand":"BMW","segment":"Adventure Touring","countryPriority":"Deutschland / DACH gebraucht","status":"planned","path":"","seatPainFocus":"Touring, niedrige/hohe Sitzbank, Komfortsitz, Sattlerumbau","whyNext":"Großer Bestand und viele Erfahrungsberichte.","slug":"bmw-r-1250-gs"}'::jsonb,
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    segment = EXCLUDED.segment,
    country_priority = EXCLUDED.country_priority,
    status = EXCLUDED.status,
    guide_path = EXCLUDED.guide_path,
    seat_pain_focus = EXCLUDED.seat_pain_focus,
    why_next = EXCLUDED.why_next,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycles (
    slug, brand, model, segment, country_priority, status, guide_path,
    seat_pain_focus, why_next, source_data, updated_at
  )
  VALUES (
    'honda-crf1100l-africa-twin',
    'Honda',
    'Honda CRF1100L Africa Twin',
    'Adventure / Reiseenduro',
    'Europa',
    'planned',
    NULL,
    'Sitzhöhe, Offroad-Bewegung, lange Etappen',
    'Sehr relevant für Reise und Mischbetrieb.',
    '{"name":"Honda CRF1100L Africa Twin","brand":"Honda","segment":"Adventure / Reiseenduro","countryPriority":"Europa","status":"planned","path":"","seatPainFocus":"Sitzhöhe, Offroad-Bewegung, lange Etappen","whyNext":"Sehr relevant für Reise und Mischbetrieb.","slug":"honda-crf1100l-africa-twin"}'::jsonb,
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    segment = EXCLUDED.segment,
    country_priority = EXCLUDED.country_priority,
    status = EXCLUDED.status,
    guide_path = EXCLUDED.guide_path,
    seat_pain_focus = EXCLUDED.seat_pain_focus,
    why_next = EXCLUDED.why_next,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycles (
    slug, brand, model, segment, country_priority, status, guide_path,
    seat_pain_focus, why_next, source_data, updated_at
  )
  VALUES (
    'yamaha-tracer-9-9-gt',
    'Yamaha',
    'Yamaha Tracer 9 / 9 GT',
    'Sport Touring',
    'Europa',
    'planned',
    NULL,
    'Touring-Komfort, Sitzneigung, Winddruck, Sozius',
    'Direkter Nachbar zur GSX-S1000GX Zielgruppe.',
    '{"name":"Yamaha Tracer 9 / 9 GT","brand":"Yamaha","segment":"Sport Touring","countryPriority":"Europa","status":"planned","path":"","seatPainFocus":"Touring-Komfort, Sitzneigung, Winddruck, Sozius","whyNext":"Direkter Nachbar zur GSX-S1000GX Zielgruppe.","slug":"yamaha-tracer-9-9-gt"}'::jsonb,
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    segment = EXCLUDED.segment,
    country_priority = EXCLUDED.country_priority,
    status = EXCLUDED.status,
    guide_path = EXCLUDED.guide_path,
    seat_pain_focus = EXCLUDED.seat_pain_focus,
    why_next = EXCLUDED.why_next,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycles (
    slug, brand, model, segment, country_priority, status, guide_path,
    seat_pain_focus, why_next, source_data, updated_at
  )
  VALUES (
    'suzuki-v-strom-1050',
    'Suzuki',
    'Suzuki V-Strom 1050',
    'Adventure Touring',
    'Europa',
    'planned',
    NULL,
    'Lange Touren, Sitzhöhe, breite Sitzbank, Zubehör',
    'Suzuki-Familie, guter Vergleich zur GSX-S1000GX.',
    '{"name":"Suzuki V-Strom 1050","brand":"Suzuki","segment":"Adventure Touring","countryPriority":"Europa","status":"planned","path":"","seatPainFocus":"Lange Touren, Sitzhöhe, breite Sitzbank, Zubehör","whyNext":"Suzuki-Familie, guter Vergleich zur GSX-S1000GX.","slug":"suzuki-v-strom-1050"}'::jsonb,
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    segment = EXCLUDED.segment,
    country_priority = EXCLUDED.country_priority,
    status = EXCLUDED.status,
    guide_path = EXCLUDED.guide_path,
    seat_pain_focus = EXCLUDED.seat_pain_focus,
    why_next = EXCLUDED.why_next,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycles (
    slug, brand, model, segment, country_priority, status, guide_path,
    seat_pain_focus, why_next, source_data, updated_at
  )
  VALUES (
    'kawasaki-versys-1000',
    'Kawasaki',
    'Kawasaki Versys 1000',
    'Crossover Touring',
    'Europa',
    'planned',
    NULL,
    'Touring, Sozius, Sitzbreite, Komfortsitz',
    'Touring-Nutzer mit ähnlicher Sitzbank-Frage.',
    '{"name":"Kawasaki Versys 1000","brand":"Kawasaki","segment":"Crossover Touring","countryPriority":"Europa","status":"planned","path":"","seatPainFocus":"Touring, Sozius, Sitzbreite, Komfortsitz","whyNext":"Touring-Nutzer mit ähnlicher Sitzbank-Frage.","slug":"kawasaki-versys-1000"}'::jsonb,
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    segment = EXCLUDED.segment,
    country_priority = EXCLUDED.country_priority,
    status = EXCLUDED.status,
    guide_path = EXCLUDED.guide_path,
    seat_pain_focus = EXCLUDED.seat_pain_focus,
    why_next = EXCLUDED.why_next,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycles (
    slug, brand, model, segment, country_priority, status, guide_path,
    seat_pain_focus, why_next, source_data, updated_at
  )
  VALUES (
    'ducati-multistrada-v4',
    'Ducati',
    'Ducati Multistrada V4',
    'Premium Adventure Touring',
    'Europa',
    'planned',
    NULL,
    'Premium-Zubehör, Hitze, lange Touren, Sitzhöhe',
    'Guter Kontrast für hochpreisige OEM/Aftermarket-Lösungen.',
    '{"name":"Ducati Multistrada V4","brand":"Ducati","segment":"Premium Adventure Touring","countryPriority":"Europa","status":"planned","path":"","seatPainFocus":"Premium-Zubehör, Hitze, lange Touren, Sitzhöhe","whyNext":"Guter Kontrast für hochpreisige OEM/Aftermarket-Lösungen.","slug":"ducati-multistrada-v4"}'::jsonb,
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    segment = EXCLUDED.segment,
    country_priority = EXCLUDED.country_priority,
    status = EXCLUDED.status,
    guide_path = EXCLUDED.guide_path,
    seat_pain_focus = EXCLUDED.seat_pain_focus,
    why_next = EXCLUDED.why_next,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycles (
    slug, brand, model, segment, country_priority, status, guide_path,
    seat_pain_focus, why_next, source_data, updated_at
  )
  VALUES (
    'honda-nc750x',
    'Honda',
    'Honda NC750X',
    'Alltag / Crossover',
    'Europa',
    'planned',
    NULL,
    'Pendeln, kurze bis mittlere Touren, Budget-Lösungen',
    'Wichtig für günstigere, alltagstaugliche Empfehlungen.',
    '{"name":"Honda NC750X","brand":"Honda","segment":"Alltag / Crossover","countryPriority":"Europa","status":"planned","path":"","seatPainFocus":"Pendeln, kurze bis mittlere Touren, Budget-Lösungen","whyNext":"Wichtig für günstigere, alltagstaugliche Empfehlungen.","slug":"honda-nc750x"}'::jsonb,
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    segment = EXCLUDED.segment,
    country_priority = EXCLUDED.country_priority,
    status = EXCLUDED.status,
    guide_path = EXCLUDED.guide_path,
    seat_pain_focus = EXCLUDED.seat_pain_focus,
    why_next = EXCLUDED.why_next,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO solution_paths (
    key, title, summary, best_for, not_ideal_for, cost, confidence, source_data, updated_at
  )
  VALUES (
    'reversible_addon',
    'Reversible Auflage testen',
    '3D-Mesh, Air Cushion oder dünne Komfortauflage testen, bevor die originale Sitzbank verändert wird.',
    'unsichere Ursache, niedriges Budget, schnelle Tests',
    'stark falsche Sitzform oder lange Touren mit klaren Druckpunkten',
    'niedrig bis mittel',
    'MVP: mittel',
    '{"key":"reversible_addon","title":"Reversible Auflage testen","summary":"3D-Mesh, Air Cushion oder dünne Komfortauflage testen, bevor die originale Sitzbank verändert wird.","bestFor":"unsichere Ursache, niedriges Budget, schnelle Tests","notIdealFor":"stark falsche Sitzform oder lange Touren mit klaren Druckpunkten","cost":"niedrig bis mittel","confidence":"MVP: mittel"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    best_for = EXCLUDED.best_for,
    not_ideal_for = EXCLUDED.not_ideal_for,
    cost = EXCLUDED.cost,
    confidence = EXCLUDED.confidence,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO solution_paths (
    key, title, summary, best_for, not_ideal_for, cost, confidence, source_data, updated_at
  )
  VALUES (
    'oem_comfort_seat',
    'OEM Komfort- oder Zubehörsitz prüfen',
    'Suzuki Zubehör kann die sauberste Plug-and-play-Option sein, muss aber mit Sitzhöhe und Rückgabemöglichkeit geprüft werden.',
    'Fahrer, die nicht schneiden oder basteln wollen',
    'wenn die OEM-Form nicht zum Körper passt',
    'mittel bis hoch',
    'MVP: braucht Quellenprüfung',
    '{"key":"oem_comfort_seat","title":"OEM Komfort- oder Zubehörsitz prüfen","summary":"Suzuki Zubehör kann die sauberste Plug-and-play-Option sein, muss aber mit Sitzhöhe und Rückgabemöglichkeit geprüft werden.","bestFor":"Fahrer, die nicht schneiden oder basteln wollen","notIdealFor":"wenn die OEM-Form nicht zum Körper passt","cost":"mittel bis hoch","confidence":"MVP: braucht Quellenprüfung"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    best_for = EXCLUDED.best_for,
    not_ideal_for = EXCLUDED.not_ideal_for,
    cost = EXCLUDED.cost,
    confidence = EXCLUDED.confidence,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO solution_paths (
    key, title, summary, best_for, not_ideal_for, cost, confidence, source_data, updated_at
  )
  VALUES (
    'aftermarket_seat',
    'Aftermarket-Sitz vergleichen',
    'Premiumsitze können auf langen Strecken helfen, sind aber teuer und nicht automatisch für jeden Körper passend.',
    'lange Touren, hohes Budget, klare Rückgaberegeln',
    'kurze sportliche Fahrten oder unklare Beschwerden',
    'hoch',
    'MVP: niedrig bis mittel',
    '{"key":"aftermarket_seat","title":"Aftermarket-Sitz vergleichen","summary":"Premiumsitze können auf langen Strecken helfen, sind aber teuer und nicht automatisch für jeden Körper passend.","bestFor":"lange Touren, hohes Budget, klare Rückgaberegeln","notIdealFor":"kurze sportliche Fahrten oder unklare Beschwerden","cost":"hoch","confidence":"MVP: niedrig bis mittel"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    best_for = EXCLUDED.best_for,
    not_ideal_for = EXCLUDED.not_ideal_for,
    cost = EXCLUDED.cost,
    confidence = EXCLUDED.confidence,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO solution_paths (
    key, title, summary, best_for, not_ideal_for, cost, confidence, source_data, updated_at
  )
  VALUES (
    'professional_upholsterer',
    'Sattler / Sitzbankumbau',
    'Ein guter Sattler kann Form, Breite, Schaum und Bezug gezielt anpassen.',
    'klare Druckpunkte, lange Nutzung des Motorrads, individuelle Anatomie',
    'wenn Rückbau und Originalzustand sehr wichtig sind',
    'mittel bis hoch',
    'MVP: mittel',
    '{"key":"professional_upholsterer","title":"Sattler / Sitzbankumbau","summary":"Ein guter Sattler kann Form, Breite, Schaum und Bezug gezielt anpassen.","bestFor":"klare Druckpunkte, lange Nutzung des Motorrads, individuelle Anatomie","notIdealFor":"wenn Rückbau und Originalzustand sehr wichtig sind","cost":"mittel bis hoch","confidence":"MVP: mittel"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    best_for = EXCLUDED.best_for,
    not_ideal_for = EXCLUDED.not_ideal_for,
    cost = EXCLUDED.cost,
    confidence = EXCLUDED.confidence,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO solution_paths (
    key, title, summary, best_for, not_ideal_for, cost, confidence, source_data, updated_at
  )
  VALUES (
    'diy',
    'DIY nur mit Plan',
    'DIY kann funktionieren, sollte aber mit Dokumentation, Messung und idealerweise einer zweiten Sitzbank starten.',
    'erfahrene Bastler und Lernprojekte',
    'einzige Original-Sitzbank, Zeitdruck oder fehlendes Werkzeug',
    'variabel',
    'MVP: abhängig von Können',
    '{"key":"diy","title":"DIY nur mit Plan","summary":"DIY kann funktionieren, sollte aber mit Dokumentation, Messung und idealerweise einer zweiten Sitzbank starten.","bestFor":"erfahrene Bastler und Lernprojekte","notIdealFor":"einzige Original-Sitzbank, Zeitdruck oder fehlendes Werkzeug","cost":"variabel","confidence":"MVP: abhängig von Können"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    best_for = EXCLUDED.best_for,
    not_ideal_for = EXCLUDED.not_ideal_for,
    cost = EXCLUDED.cost,
    confidence = EXCLUDED.confidence,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO product_categories (
    key, name, problem_solved, limitations, price_band, first_test,
    avoid_when, buying_checks, affiliate_status, source_data, updated_at
  )
  VALUES (
    '3d_mesh_cover',
    '3D-Mesh Sitzauflage',
    'Hitze, Schwitzen, leichte Druckverteilung',
    'erhöht Sitzhöhe leicht und löst keine falsche Sitzform',
    'niedrig',
    'Eine einzelne 60- bis 90-Minuten-Fahrt bei warmem Wetter mit gleicher Hose und gleicher Strecke.',
    'du schon ohne Auflage kaum sicher mit den Füßen auf den Boden kommst.',
    '["passende Größe für die GSX-S1000GX Sitzfläche","sichere Befestigung ohne Rutschen","keine harten Nähte oder Kanten im Sitzbereich","einfache Rückgabe, falls Sitzhöhe oder Gefühl stören"]'::jsonb,
    'affiliate candidate',
    '{"key":"3d_mesh_cover","name":"3D-Mesh Sitzauflage","problemSolved":"Hitze, Schwitzen, leichte Druckverteilung","limitations":"erhöht Sitzhöhe leicht und löst keine falsche Sitzform","priceBand":"niedrig","firstTest":"Eine einzelne 60- bis 90-Minuten-Fahrt bei warmem Wetter mit gleicher Hose und gleicher Strecke.","avoidWhen":"du schon ohne Auflage kaum sicher mit den Füßen auf den Boden kommst.","buyingChecks":["passende Größe für die GSX-S1000GX Sitzfläche","sichere Befestigung ohne Rutschen","keine harten Nähte oder Kanten im Sitzbereich","einfache Rückgabe, falls Sitzhöhe oder Gefühl stören"],"affiliateStatus":"affiliate candidate"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    problem_solved = EXCLUDED.problem_solved,
    limitations = EXCLUDED.limitations,
    price_band = EXCLUDED.price_band,
    first_test = EXCLUDED.first_test,
    avoid_when = EXCLUDED.avoid_when,
    buying_checks = EXCLUDED.buying_checks,
    affiliate_status = EXCLUDED.affiliate_status,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO product_categories (
    key, name, problem_solved, limitations, price_band, first_test,
    avoid_when, buying_checks, affiliate_status, source_data, updated_at
  )
  VALUES (
    'air_cushion',
    'Luftkissen',
    'Druckentlastung auf längeren geraden Strecken',
    'kann entkoppelt wirken und muss sehr niedrig aufgepumpt werden',
    'mittel',
    'Sehr wenig Luft verwenden und erst auf ruhiger Strecke testen, nicht direkt auf einer schnellen Tour.',
    'du sportlich fährst und direkten Kontakt zum Motorrad brauchst.',
    '["Form passt zur Sitzbank und engt nicht an den Oberschenkeln ein","Ventil stört nicht beim Sitzen","Befestigung bleibt beim Auf- und Absteigen stabil","Material ist hitze- und UV-tauglich"]'::jsonb,
    'affiliate candidate',
    '{"key":"air_cushion","name":"Luftkissen","problemSolved":"Druckentlastung auf längeren geraden Strecken","limitations":"kann entkoppelt wirken und muss sehr niedrig aufgepumpt werden","priceBand":"mittel","firstTest":"Sehr wenig Luft verwenden und erst auf ruhiger Strecke testen, nicht direkt auf einer schnellen Tour.","avoidWhen":"du sportlich fährst und direkten Kontakt zum Motorrad brauchst.","buyingChecks":["Form passt zur Sitzbank und engt nicht an den Oberschenkeln ein","Ventil stört nicht beim Sitzen","Befestigung bleibt beim Auf- und Absteigen stabil","Material ist hitze- und UV-tauglich"],"affiliateStatus":"affiliate candidate"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    problem_solved = EXCLUDED.problem_solved,
    limitations = EXCLUDED.limitations,
    price_band = EXCLUDED.price_band,
    first_test = EXCLUDED.first_test,
    avoid_when = EXCLUDED.avoid_when,
    buying_checks = EXCLUDED.buying_checks,
    affiliate_status = EXCLUDED.affiliate_status,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO product_categories (
    key, name, problem_solved, limitations, price_band, first_test,
    avoid_when, buying_checks, affiliate_status, source_data, updated_at
  )
  VALUES (
    'gel_pad',
    'Gel-Pad',
    'kurzfristige Druckminderung für manche Fahrer',
    'kann Hitze speichern und schlechte Form nicht reparieren',
    'niedrig bis mittel',
    'Nur als reversible Auflage testen, bevor Gel in die Sitzbank eingebaut wird.',
    'dein Hauptproblem Hitze, Rutschen oder eine falsche Sitzform ist.',
    '["Dicke und Kantenverlauf prüfen","Temperaturverhalten bei Sonne beachten","Rückgabe möglich halten","nicht als Allheilmittel für Langstrecke betrachten"]'::jsonb,
    'caution',
    '{"key":"gel_pad","name":"Gel-Pad","problemSolved":"kurzfristige Druckminderung für manche Fahrer","limitations":"kann Hitze speichern und schlechte Form nicht reparieren","priceBand":"niedrig bis mittel","firstTest":"Nur als reversible Auflage testen, bevor Gel in die Sitzbank eingebaut wird.","avoidWhen":"dein Hauptproblem Hitze, Rutschen oder eine falsche Sitzform ist.","buyingChecks":["Dicke und Kantenverlauf prüfen","Temperaturverhalten bei Sonne beachten","Rückgabe möglich halten","nicht als Allheilmittel für Langstrecke betrachten"],"affiliateStatus":"caution"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    problem_solved = EXCLUDED.problem_solved,
    limitations = EXCLUDED.limitations,
    price_band = EXCLUDED.price_band,
    first_test = EXCLUDED.first_test,
    avoid_when = EXCLUDED.avoid_when,
    buying_checks = EXCLUDED.buying_checks,
    affiliate_status = EXCLUDED.affiliate_status,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO product_categories (
    key, name, problem_solved, limitations, price_band, first_test,
    avoid_when, buying_checks, affiliate_status, source_data, updated_at
  )
  VALUES (
    'professional_upholstery',
    'Professioneller Sitzbankumbau',
    'Form, Schaum, Breite und Bezug gezielt anpassen',
    'Qualität hängt stark vom Sattler ab, Rückbau nicht immer möglich',
    'mittel bis hoch',
    'Vorher Fotos, Maße, Beschwerden und gewünschte Nutzung dokumentieren.',
    'du noch nicht weißt, ob Druck, Hitze, Rutschen oder Kniewinkel das eigentliche Problem ist.',
    '["Referenzarbeiten und echte Kundenfotos prüfen","Materialaufbau schriftlich klären","Wasserdichtigkeit und Bezug prüfen","Originalsitz oder Zweitsitz als Basis besprechen"]'::jsonb,
    'service listing later',
    '{"key":"professional_upholstery","name":"Professioneller Sitzbankumbau","problemSolved":"Form, Schaum, Breite und Bezug gezielt anpassen","limitations":"Qualität hängt stark vom Sattler ab, Rückbau nicht immer möglich","priceBand":"mittel bis hoch","firstTest":"Vorher Fotos, Maße, Beschwerden und gewünschte Nutzung dokumentieren.","avoidWhen":"du noch nicht weißt, ob Druck, Hitze, Rutschen oder Kniewinkel das eigentliche Problem ist.","buyingChecks":["Referenzarbeiten und echte Kundenfotos prüfen","Materialaufbau schriftlich klären","Wasserdichtigkeit und Bezug prüfen","Originalsitz oder Zweitsitz als Basis besprechen"],"affiliateStatus":"service listing later"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    problem_solved = EXCLUDED.problem_solved,
    limitations = EXCLUDED.limitations,
    price_band = EXCLUDED.price_band,
    first_test = EXCLUDED.first_test,
    avoid_when = EXCLUDED.avoid_when,
    buying_checks = EXCLUDED.buying_checks,
    affiliate_status = EXCLUDED.affiliate_status,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO product_categories (
    key, name, problem_solved, limitations, price_band, first_test,
    avoid_when, buying_checks, affiliate_status, source_data, updated_at
  )
  VALUES (
    'oem_comfort_seat',
    'OEM Komfortsitz',
    'Plug-and-play Lösung ohne eigene Umbauten',
    'passt nicht automatisch zu jedem Körper und kann teuer sein',
    'mittel bis hoch',
    'Nur kaufen, wenn Teilenummer, Modelljahr und Rückgabe eindeutig sind.',
    'du eine stark individuelle Schmerzstelle hast oder die OEM-Form dein Problem ist.',
    '["Teilenummer für Modelljahr prüfen","Sitzhöhe und eventuelle Änderung klären","Rückgabe bei montierter Ware prüfen","Besitzerberichte speziell zur GSX-S1000GX suchen"]'::jsonb,
    'research needed',
    '{"key":"oem_comfort_seat","name":"OEM Komfortsitz","problemSolved":"Plug-and-play Lösung ohne eigene Umbauten","limitations":"passt nicht automatisch zu jedem Körper und kann teuer sein","priceBand":"mittel bis hoch","firstTest":"Nur kaufen, wenn Teilenummer, Modelljahr und Rückgabe eindeutig sind.","avoidWhen":"du eine stark individuelle Schmerzstelle hast oder die OEM-Form dein Problem ist.","buyingChecks":["Teilenummer für Modelljahr prüfen","Sitzhöhe und eventuelle Änderung klären","Rückgabe bei montierter Ware prüfen","Besitzerberichte speziell zur GSX-S1000GX suchen"],"affiliateStatus":"research needed"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    problem_solved = EXCLUDED.problem_solved,
    limitations = EXCLUDED.limitations,
    price_band = EXCLUDED.price_band,
    first_test = EXCLUDED.first_test,
    avoid_when = EXCLUDED.avoid_when,
    buying_checks = EXCLUDED.buying_checks,
    affiliate_status = EXCLUDED.affiliate_status,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO product_categories (
    key, name, problem_solved, limitations, price_band, first_test,
    avoid_when, buying_checks, affiliate_status, source_data, updated_at
  )
  VALUES (
    'aftermarket_seat',
    'Aftermarket Komplettsitz',
    'Langstreckenkomfort, breitere Auflage und definierte Form',
    'hochpreisig, Lieferzeit und Rückgabe können kritisch sein',
    'hoch',
    'Erst kaufen, wenn echte Erfahrungsberichte zum Motorradmodell und Rückgaberegeln passen.',
    'du nur kurze Runden fährst oder unklar ist, woher der Schmerz kommt.',
    '["Lieferland, Zoll und Rückgabe prüfen","Sitzhöhe, Breite und Soziusbereich vergleichen","Bewertungen nach Körpergröße und Fahrtyp filtern","keine Herstellerwerbung mit Erfahrungswerten verwechseln"]'::jsonb,
    'research needed',
    '{"key":"aftermarket_seat","name":"Aftermarket Komplettsitz","problemSolved":"Langstreckenkomfort, breitere Auflage und definierte Form","limitations":"hochpreisig, Lieferzeit und Rückgabe können kritisch sein","priceBand":"hoch","firstTest":"Erst kaufen, wenn echte Erfahrungsberichte zum Motorradmodell und Rückgaberegeln passen.","avoidWhen":"du nur kurze Runden fährst oder unklar ist, woher der Schmerz kommt.","buyingChecks":["Lieferland, Zoll und Rückgabe prüfen","Sitzhöhe, Breite und Soziusbereich vergleichen","Bewertungen nach Körpergröße und Fahrtyp filtern","keine Herstellerwerbung mit Erfahrungswerten verwechseln"],"affiliateStatus":"research needed"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    problem_solved = EXCLUDED.problem_solved,
    limitations = EXCLUDED.limitations,
    price_band = EXCLUDED.price_band,
    first_test = EXCLUDED.first_test,
    avoid_when = EXCLUDED.avoid_when,
    buying_checks = EXCLUDED.buying_checks,
    affiliate_status = EXCLUDED.affiliate_status,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO seat_options (
    key, motorcycle_slug, name, maker, option_type, fitment, market, price_note,
    best_for, watch_out, comfort_logic, research_status, confidence,
    affiliate_status, image_path, image_alt, source_label, source_url, source_data, updated_at
  )
  VALUES (
    'suzuki-premium-seat-de',
    'suzuki-gsx-s1000gx',
    'Suzuki Premium-Sitz Set',
    'Suzuki',
    'OEM comfort seat',
    'GSX-S1000GX, Teilenummer 45100-48820-000 / 45100-48820',
    'Deutschland / Suzuki OEM',
    'Suzuki Deutschland listete 431,55 EUR; Suzuki USA listete 449,95 USD. Vor Kauf lokal erneut prüfen.',
    'Fahrer, die eine plug-and-play Lösung mit OEM-Passform wollen und keine stark individuelle Schmerzstelle haben.',
    'Nicht automatisch die beste Lösung, wenn die originale Sitzform oder Sitzneigung dein Hauptproblem ist.',
    'Zweilagige Urethanschaum-Konstruktion, griffigere Oberflaeche und laut Suzuki geringere Oberflaechentemperatur bei Sonne.',
    'verified source, needs owner feedback',
    4,
    'dealer / affiliate later',
    '/assets/options/comfort-seat.svg',
    'Illustration eines schwarzen Komfort-Motorradsitzes',
    'Suzuki Deutschland',
    'https://motorrad.suzuki.de/modelle/street/gsx-s1000gx/zubehoer/premium-sitz',
    '{"key":"suzuki-premium-seat-de","name":"Suzuki Premium-Sitz Set","maker":"Suzuki","type":"OEM comfort seat","fitment":"GSX-S1000GX, Teilenummer 45100-48820-000 / 45100-48820","market":"Deutschland / Suzuki OEM","priceNote":"Suzuki Deutschland listete 431,55 EUR; Suzuki USA listete 449,95 USD. Vor Kauf lokal erneut prüfen.","bestFor":"Fahrer, die eine plug-and-play Lösung mit OEM-Passform wollen und keine stark individuelle Schmerzstelle haben.","watchOut":"Nicht automatisch die beste Lösung, wenn die originale Sitzform oder Sitzneigung dein Hauptproblem ist.","comfortLogic":"Zweilagige Urethanschaum-Konstruktion, griffigere Oberflaeche und laut Suzuki geringere Oberflaechentemperatur bei Sonne.","researchStatus":"verified source, needs owner feedback","confidence":4,"affiliateStatus":"dealer / affiliate later","imagePath":"/assets/options/comfort-seat.svg","imageAlt":"Illustration eines schwarzen Komfort-Motorradsitzes","sourceLabel":"Suzuki Deutschland","sourceUrl":"https://motorrad.suzuki.de/modelle/street/gsx-s1000gx/zubehoer/premium-sitz"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    motorcycle_slug = EXCLUDED.motorcycle_slug,
    name = EXCLUDED.name,
    maker = EXCLUDED.maker,
    option_type = EXCLUDED.option_type,
    fitment = EXCLUDED.fitment,
    market = EXCLUDED.market,
    price_note = EXCLUDED.price_note,
    best_for = EXCLUDED.best_for,
    watch_out = EXCLUDED.watch_out,
    comfort_logic = EXCLUDED.comfort_logic,
    research_status = EXCLUDED.research_status,
    confidence = EXCLUDED.confidence,
    affiliate_status = EXCLUDED.affiliate_status,
    image_path = EXCLUDED.image_path,
    image_alt = EXCLUDED.image_alt,
    source_label = EXCLUDED.source_label,
    source_url = EXCLUDED.source_url,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO seat_options (
    key, motorcycle_slug, name, maker, option_type, fitment, market, price_note,
    best_for, watch_out, comfort_logic, research_status, confidence,
    affiliate_status, image_path, image_alt, source_label, source_url, source_data, updated_at
  )
  VALUES (
    'sargent-world-sport-front',
    'suzuki-gsx-s1000gx',
    'Sargent World Sport Front Seat',
    'Sargent',
    'aftermarket front seat',
    'GSX-S1000GX 2024+ laut Sargent Produktseiten',
    'USA / UK Import möglich',
    'US-Listenpreise für Front-Sitz lagen je nach Variante um 429,95 bis 639,95 USD; UK-Import kann Zoll, Versand und Rückgabe verändern.',
    'Tourenfahrer mit Budget, die eine breitere definierte Sitzform und einen Komplettsitz statt Auflage suchen.',
    'Teuer, Rückgabe/Restocking Fee, Lieferzeit und Importkosten vorher klären. Für kurze Runden oft überdimensioniert.',
    'Sargent nennt breiteren Sitzpan, Performance-Plus/DTX Varianten und optionale Heizung je nach Ausfuehrung.',
    'verified source, needs EU fitment and return check',
    3,
    'research affiliate later',
    '/assets/options/comfort-seat.svg',
    'Illustration eines breiteren Touring-Motorradsitzes',
    'Sargent Cycle',
    'https://www.sargentcycle.com/seats/suzuki/gsxs1000/gsxs1000gx?order=relevance%3Adesc&show=24',
    '{"key":"sargent-world-sport-front","name":"Sargent World Sport Front Seat","maker":"Sargent","type":"aftermarket front seat","fitment":"GSX-S1000GX 2024+ laut Sargent Produktseiten","market":"USA / UK Import möglich","priceNote":"US-Listenpreise für Front-Sitz lagen je nach Variante um 429,95 bis 639,95 USD; UK-Import kann Zoll, Versand und Rückgabe verändern.","bestFor":"Tourenfahrer mit Budget, die eine breitere definierte Sitzform und einen Komplettsitz statt Auflage suchen.","watchOut":"Teuer, Rückgabe/Restocking Fee, Lieferzeit und Importkosten vorher klären. Für kurze Runden oft überdimensioniert.","comfortLogic":"Sargent nennt breiteren Sitzpan, Performance-Plus/DTX Varianten und optionale Heizung je nach Ausfuehrung.","researchStatus":"verified source, needs EU fitment and return check","confidence":3,"affiliateStatus":"research affiliate later","imagePath":"/assets/options/comfort-seat.svg","imageAlt":"Illustration eines breiteren Touring-Motorradsitzes","sourceLabel":"Sargent Cycle","sourceUrl":"https://www.sargentcycle.com/seats/suzuki/gsxs1000/gsxs1000gx?order=relevance%3Adesc&show=24"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    motorcycle_slug = EXCLUDED.motorcycle_slug,
    name = EXCLUDED.name,
    maker = EXCLUDED.maker,
    option_type = EXCLUDED.option_type,
    fitment = EXCLUDED.fitment,
    market = EXCLUDED.market,
    price_note = EXCLUDED.price_note,
    best_for = EXCLUDED.best_for,
    watch_out = EXCLUDED.watch_out,
    comfort_logic = EXCLUDED.comfort_logic,
    research_status = EXCLUDED.research_status,
    confidence = EXCLUDED.confidence,
    affiliate_status = EXCLUDED.affiliate_status,
    image_path = EXCLUDED.image_path,
    image_alt = EXCLUDED.image_alt,
    source_label = EXCLUDED.source_label,
    source_url = EXCLUDED.source_url,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO seat_options (
    key, motorcycle_slug, name, maker, option_type, fitment, market, price_note,
    best_for, watch_out, comfort_logic, research_status, confidence,
    affiliate_status, image_path, image_alt, source_label, source_url, source_data, updated_at
  )
  VALUES (
    '3d-mesh-first-test',
    'suzuki-gsx-s1000gx',
    '3D-Mesh Auflage als erster Test',
    'Generic / mehrere Anbieter',
    'reversible add-on',
    'Größe und Befestigung müssen zur GSX-S1000GX Sitzfläche passen',
    'Amazon, Motorradshops, Direktanbieter',
    'Niedrige bis mittlere Kosten; konkrete Links erst nach Affiliate- und Qualitätsprüfung.',
    'Hitze, Schwitzen, leichtes Druckgefühl und alle, die vor einem teuren Sitz erst etwas Rückbaubares testen wollen.',
    'Erhöht die Sitzhöhe leicht, kann rutschen und löst keine falsche Sitzform.',
    'Mehr Luftzirkulation zwischen Hose und Sitz; sinnvoll vor allem bei warmem Wetter und längeren Etappen.',
    'category validated, product shortlist needed',
    3,
    'strong affiliate candidate',
    '/assets/options/mesh-pad.svg',
    'Illustration einer 3D-Mesh Motorrad-Sitzauflage',
    'Forum and category research',
    'https://www.gsxs1000.org/threads/gx-seat-options.48928/',
    '{"key":"3d-mesh-first-test","name":"3D-Mesh Auflage als erster Test","maker":"Generic / mehrere Anbieter","type":"reversible add-on","fitment":"Größe und Befestigung müssen zur GSX-S1000GX Sitzfläche passen","market":"Amazon, Motorradshops, Direktanbieter","priceNote":"Niedrige bis mittlere Kosten; konkrete Links erst nach Affiliate- und Qualitätsprüfung.","bestFor":"Hitze, Schwitzen, leichtes Druckgefühl und alle, die vor einem teuren Sitz erst etwas Rückbaubares testen wollen.","watchOut":"Erhöht die Sitzhöhe leicht, kann rutschen und löst keine falsche Sitzform.","comfortLogic":"Mehr Luftzirkulation zwischen Hose und Sitz; sinnvoll vor allem bei warmem Wetter und längeren Etappen.","researchStatus":"category validated, product shortlist needed","confidence":3,"affiliateStatus":"strong affiliate candidate","imagePath":"/assets/options/mesh-pad.svg","imageAlt":"Illustration einer 3D-Mesh Motorrad-Sitzauflage","sourceLabel":"Forum and category research","sourceUrl":"https://www.gsxs1000.org/threads/gx-seat-options.48928/"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    motorcycle_slug = EXCLUDED.motorcycle_slug,
    name = EXCLUDED.name,
    maker = EXCLUDED.maker,
    option_type = EXCLUDED.option_type,
    fitment = EXCLUDED.fitment,
    market = EXCLUDED.market,
    price_note = EXCLUDED.price_note,
    best_for = EXCLUDED.best_for,
    watch_out = EXCLUDED.watch_out,
    comfort_logic = EXCLUDED.comfort_logic,
    research_status = EXCLUDED.research_status,
    confidence = EXCLUDED.confidence,
    affiliate_status = EXCLUDED.affiliate_status,
    image_path = EXCLUDED.image_path,
    image_alt = EXCLUDED.image_alt,
    source_label = EXCLUDED.source_label,
    source_url = EXCLUDED.source_url,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO seat_options (
    key, motorcycle_slug, name, maker, option_type, fitment, market, price_note,
    best_for, watch_out, comfort_logic, research_status, confidence,
    affiliate_status, image_path, image_alt, source_label, source_url, source_data, updated_at
  )
  VALUES (
    'local-upholstery-custom',
    'suzuki-gsx-s1000gx',
    'Lokaler Sattler / Sitzbankumbau',
    'Regionaler Sattler',
    'custom upholstery',
    'Originalsitz oder Zweitsitz als Basis',
    'Deutschland / DACH lokal',
    'Preis stark abhaengig von Schaumaufbau, Bezug, Naehten, Heizung und Abdichtung.',
    'Klare Schmerzstelle, spezieller Körperbau, Wunsch nach anderer Form, Höhe oder Bezug.',
    'Qualität variiert stark. Fotos, Materialaufbau, Wasserdichtigkeit und Rückbau vorher schriftlich klären.',
    'Form, Breite, Kanten, Schaumhaerte und Bezug koennen gezielt an den Fahrer angepasst werden.',
    'needs local provider database',
    2,
    'service directory later',
    '/assets/options/upholstery-workshop.svg',
    'Illustration einer Sitzbank im Sattler-Workshop',
    'Moto Seat Lab research backlog',
    '/de/diy/',
    '{"key":"local-upholstery-custom","name":"Lokaler Sattler / Sitzbankumbau","maker":"Regionaler Sattler","type":"custom upholstery","fitment":"Originalsitz oder Zweitsitz als Basis","market":"Deutschland / DACH lokal","priceNote":"Preis stark abhaengig von Schaumaufbau, Bezug, Naehten, Heizung und Abdichtung.","bestFor":"Klare Schmerzstelle, spezieller Körperbau, Wunsch nach anderer Form, Höhe oder Bezug.","watchOut":"Qualität variiert stark. Fotos, Materialaufbau, Wasserdichtigkeit und Rückbau vorher schriftlich klären.","comfortLogic":"Form, Breite, Kanten, Schaumhaerte und Bezug koennen gezielt an den Fahrer angepasst werden.","researchStatus":"needs local provider database","confidence":2,"affiliateStatus":"service directory later","imagePath":"/assets/options/upholstery-workshop.svg","imageAlt":"Illustration einer Sitzbank im Sattler-Workshop","sourceLabel":"Moto Seat Lab research backlog","sourceUrl":"/de/diy/"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    motorcycle_slug = EXCLUDED.motorcycle_slug,
    name = EXCLUDED.name,
    maker = EXCLUDED.maker,
    option_type = EXCLUDED.option_type,
    fitment = EXCLUDED.fitment,
    market = EXCLUDED.market,
    price_note = EXCLUDED.price_note,
    best_for = EXCLUDED.best_for,
    watch_out = EXCLUDED.watch_out,
    comfort_logic = EXCLUDED.comfort_logic,
    research_status = EXCLUDED.research_status,
    confidence = EXCLUDED.confidence,
    affiliate_status = EXCLUDED.affiliate_status,
    image_path = EXCLUDED.image_path,
    image_alt = EXCLUDED.image_alt,
    source_label = EXCLUDED.source_label,
    source_url = EXCLUDED.source_url,
    source_data = EXCLUDED.source_data,
    updated_at = now();
DELETE FROM research_sources WHERE motorcycle_slug = 'suzuki-gsx-s1000gx';
INSERT INTO research_sources (
    motorcycle_slug, title, url, notes, confidence, source_data, updated_at
  )
  VALUES (
    'suzuki-gsx-s1000gx',
    'Suzuki Global GSX-S1000GX',
    'https://www.globalsuzuki.com/motorcycle/smgs/products/2024gsx-s1000gx/',
    'Official model source. Seat accessory details need separate verification.',
    5,
    '{"title":"Suzuki Global GSX-S1000GX","url":"https://www.globalsuzuki.com/motorcycle/smgs/products/2024gsx-s1000gx/","type":"manufacturer_official","confidence":5,"notes":"Official model source. Seat accessory details need separate verification."}'::jsonb,
    now()
  );
INSERT INTO research_sources (
    motorcycle_slug, title, url, notes, confidence, source_data, updated_at
  )
  VALUES (
    'suzuki-gsx-s1000gx',
    'Suzuki USA GSX-S1000GX accessory catalog',
    'https://store.suzukicycles.com/c/accessories_standard_gsx-s1000gx',
    'Useful for accessory naming and availability; Germany availability must be verified separately.',
    4,
    '{"title":"Suzuki USA GSX-S1000GX accessory catalog","url":"https://store.suzukicycles.com/c/accessories_standard_gsx-s1000gx","type":"manufacturer_accessory_catalog","confidence":4,"notes":"Useful for accessory naming and availability; Germany availability must be verified separately."}'::jsonb,
    now()
  );
INSERT INTO research_sources (
    motorcycle_slug, title, url, notes, confidence, source_data, updated_at
  )
  VALUES (
    'suzuki-gsx-s1000gx',
    'Global forum seat pain research',
    'https://github.com/sokolicek/moto-seat-lab/blob/main/docs/research/global-forum-seat-pain-research.md',
    'Anecdotal pain-point research, not product proof.',
    2,
    '{"title":"Global forum seat pain research","url":"https://github.com/sokolicek/moto-seat-lab/blob/main/docs/research/global-forum-seat-pain-research.md","type":"research_note","confidence":2,"notes":"Anecdotal pain-point research, not product proof."}'::jsonb,
    now()
  );
INSERT INTO import_runs (label, row_counts)
VALUES ('json seed import', '{"countries":1,"motorcycles":9,"solution_paths":5,"product_categories":6,"seat_options":4,"research_sources":3}'::jsonb);
COMMIT;
