-- Generated by scripts/generate-seed-sql.mjs. Do not edit by hand.
-- Re-run `make db-seed` after changing JSON source data.

BEGIN;
INSERT INTO countries (code, name, language_code, market_notes, source_data, updated_at)
VALUES (
  'de',
  'Deutschland',
  'de',
  'German pilot market',
  '{"country":"DE","language":"de","currency":"EUR","designVariant":"technical_touring","marketGroup":"premium_touring","defaultSolutionOrder":["diagnose_problem","reversible_addon","oem_comfort_seat","aftermarket_seat","professional_upholsterer","diy"],"cookieMode":"minimal_bottom_bar","premiumAftermarketVisibility":"high","localRepairVisibility":"medium"}'::jsonb,
  now()
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  language_code = EXCLUDED.language_code,
  market_notes = EXCLUDED.market_notes,
  source_data = EXCLUDED.source_data,
  updated_at = now();
INSERT INTO motorcycles (
    slug, brand, model, segment, country_priority, status, guide_path,
    seat_pain_focus, why_next, source_data, updated_at
  )
  VALUES (
    'suzuki-gsx-s1000gx',
    'Suzuki',
    'Suzuki GSX-S1000GX',
    'Sport-Tourer / Crossover',
    'Deutschland MVP',
    'active',
    '/de/motorrad-sitzbank/suzuki-gsx-s1000gx/',
    'Druck nach 45 bis 90 Minuten, Hitze, Sitzwinkel, Touring-Komfort',
    'Dein zuletzt bearbeitetes Motorrad und aktueller Referenz-Guide.',
    '{"name":"Suzuki GSX-S1000GX","brand":"Suzuki","segment":"Sport-Tourer / Crossover","countryPriority":"Deutschland MVP","status":"active","path":"/de/motorrad-sitzbank/suzuki-gsx-s1000gx/","seatPainFocus":"Druck nach 45 bis 90 Minuten, Hitze, Sitzwinkel, Touring-Komfort","whyNext":"Dein zuletzt bearbeitetes Motorrad und aktueller Referenz-Guide.","slug":"suzuki-gsx-s1000gx"}'::jsonb,
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    segment = EXCLUDED.segment,
    country_priority = EXCLUDED.country_priority,
    status = EXCLUDED.status,
    guide_path = EXCLUDED.guide_path,
    seat_pain_focus = EXCLUDED.seat_pain_focus,
    why_next = EXCLUDED.why_next,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycles (
    slug, brand, model, segment, country_priority, status, guide_path,
    seat_pain_focus, why_next, source_data, updated_at
  )
  VALUES (
    'bmw-r-1300-gs',
    'BMW',
    'BMW R 1300 GS',
    'Adventure Touring',
    'Deutschland / DACH',
    'planned',
    NULL,
    'Langstrecke, hohe Sitzbank, Sozius, Zubehörvielfalt',
    'Sehr verbreitete Reisemaschine mit vielen Sitzbankoptionen.',
    '{"name":"BMW R 1300 GS","brand":"BMW","segment":"Adventure Touring","countryPriority":"Deutschland / DACH","status":"planned","path":"","seatPainFocus":"Langstrecke, hohe Sitzbank, Sozius, Zubehörvielfalt","whyNext":"Sehr verbreitete Reisemaschine mit vielen Sitzbankoptionen.","slug":"bmw-r-1300-gs"}'::jsonb,
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    segment = EXCLUDED.segment,
    country_priority = EXCLUDED.country_priority,
    status = EXCLUDED.status,
    guide_path = EXCLUDED.guide_path,
    seat_pain_focus = EXCLUDED.seat_pain_focus,
    why_next = EXCLUDED.why_next,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycles (
    slug, brand, model, segment, country_priority, status, guide_path,
    seat_pain_focus, why_next, source_data, updated_at
  )
  VALUES (
    'bmw-r-1250-gs',
    'BMW',
    'BMW R 1250 GS',
    'Adventure Touring',
    'Deutschland / DACH gebraucht',
    'planned',
    NULL,
    'Touring, niedrige/hohe Sitzbank, Komfortsitz, Sattlerumbau',
    'Großer Bestand und viele Erfahrungsberichte.',
    '{"name":"BMW R 1250 GS","brand":"BMW","segment":"Adventure Touring","countryPriority":"Deutschland / DACH gebraucht","status":"planned","path":"","seatPainFocus":"Touring, niedrige/hohe Sitzbank, Komfortsitz, Sattlerumbau","whyNext":"Großer Bestand und viele Erfahrungsberichte.","slug":"bmw-r-1250-gs"}'::jsonb,
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    segment = EXCLUDED.segment,
    country_priority = EXCLUDED.country_priority,
    status = EXCLUDED.status,
    guide_path = EXCLUDED.guide_path,
    seat_pain_focus = EXCLUDED.seat_pain_focus,
    why_next = EXCLUDED.why_next,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycles (
    slug, brand, model, segment, country_priority, status, guide_path,
    seat_pain_focus, why_next, source_data, updated_at
  )
  VALUES (
    'honda-crf1100l-africa-twin',
    'Honda',
    'Honda CRF1100L Africa Twin',
    'Adventure / Reiseenduro',
    'Europa',
    'planned',
    NULL,
    'Sitzhöhe, Offroad-Bewegung, lange Etappen',
    'Sehr relevant für Reise und Mischbetrieb.',
    '{"name":"Honda CRF1100L Africa Twin","brand":"Honda","segment":"Adventure / Reiseenduro","countryPriority":"Europa","status":"planned","path":"","seatPainFocus":"Sitzhöhe, Offroad-Bewegung, lange Etappen","whyNext":"Sehr relevant für Reise und Mischbetrieb.","slug":"honda-crf1100l-africa-twin"}'::jsonb,
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    segment = EXCLUDED.segment,
    country_priority = EXCLUDED.country_priority,
    status = EXCLUDED.status,
    guide_path = EXCLUDED.guide_path,
    seat_pain_focus = EXCLUDED.seat_pain_focus,
    why_next = EXCLUDED.why_next,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycles (
    slug, brand, model, segment, country_priority, status, guide_path,
    seat_pain_focus, why_next, source_data, updated_at
  )
  VALUES (
    'yamaha-tracer-9-9-gt',
    'Yamaha',
    'Yamaha Tracer 9 / 9 GT',
    'Sport Touring',
    'Europa',
    'planned',
    NULL,
    'Touring-Komfort, Sitzneigung, Winddruck, Sozius',
    'Direkter Nachbar zur GSX-S1000GX Zielgruppe.',
    '{"name":"Yamaha Tracer 9 / 9 GT","brand":"Yamaha","segment":"Sport Touring","countryPriority":"Europa","status":"planned","path":"","seatPainFocus":"Touring-Komfort, Sitzneigung, Winddruck, Sozius","whyNext":"Direkter Nachbar zur GSX-S1000GX Zielgruppe.","slug":"yamaha-tracer-9-9-gt"}'::jsonb,
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    segment = EXCLUDED.segment,
    country_priority = EXCLUDED.country_priority,
    status = EXCLUDED.status,
    guide_path = EXCLUDED.guide_path,
    seat_pain_focus = EXCLUDED.seat_pain_focus,
    why_next = EXCLUDED.why_next,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycles (
    slug, brand, model, segment, country_priority, status, guide_path,
    seat_pain_focus, why_next, source_data, updated_at
  )
  VALUES (
    'suzuki-v-strom-1050',
    'Suzuki',
    'Suzuki V-Strom 1050',
    'Adventure Touring',
    'Europa',
    'planned',
    NULL,
    'Lange Touren, Sitzhöhe, breite Sitzbank, Zubehör',
    'Suzuki-Familie, guter Vergleich zur GSX-S1000GX.',
    '{"name":"Suzuki V-Strom 1050","brand":"Suzuki","segment":"Adventure Touring","countryPriority":"Europa","status":"planned","path":"","seatPainFocus":"Lange Touren, Sitzhöhe, breite Sitzbank, Zubehör","whyNext":"Suzuki-Familie, guter Vergleich zur GSX-S1000GX.","slug":"suzuki-v-strom-1050"}'::jsonb,
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    segment = EXCLUDED.segment,
    country_priority = EXCLUDED.country_priority,
    status = EXCLUDED.status,
    guide_path = EXCLUDED.guide_path,
    seat_pain_focus = EXCLUDED.seat_pain_focus,
    why_next = EXCLUDED.why_next,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycles (
    slug, brand, model, segment, country_priority, status, guide_path,
    seat_pain_focus, why_next, source_data, updated_at
  )
  VALUES (
    'kawasaki-versys-1000',
    'Kawasaki',
    'Kawasaki Versys 1000',
    'Crossover Touring',
    'Europa',
    'planned',
    NULL,
    'Touring, Sozius, Sitzbreite, Komfortsitz',
    'Touring-Nutzer mit ähnlicher Sitzbank-Frage.',
    '{"name":"Kawasaki Versys 1000","brand":"Kawasaki","segment":"Crossover Touring","countryPriority":"Europa","status":"planned","path":"","seatPainFocus":"Touring, Sozius, Sitzbreite, Komfortsitz","whyNext":"Touring-Nutzer mit ähnlicher Sitzbank-Frage.","slug":"kawasaki-versys-1000"}'::jsonb,
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    segment = EXCLUDED.segment,
    country_priority = EXCLUDED.country_priority,
    status = EXCLUDED.status,
    guide_path = EXCLUDED.guide_path,
    seat_pain_focus = EXCLUDED.seat_pain_focus,
    why_next = EXCLUDED.why_next,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycles (
    slug, brand, model, segment, country_priority, status, guide_path,
    seat_pain_focus, why_next, source_data, updated_at
  )
  VALUES (
    'ducati-multistrada-v4',
    'Ducati',
    'Ducati Multistrada V4',
    'Premium Adventure Touring',
    'Europa',
    'planned',
    NULL,
    'Premium-Zubehör, Hitze, lange Touren, Sitzhöhe',
    'Guter Kontrast für hochpreisige OEM/Aftermarket-Lösungen.',
    '{"name":"Ducati Multistrada V4","brand":"Ducati","segment":"Premium Adventure Touring","countryPriority":"Europa","status":"planned","path":"","seatPainFocus":"Premium-Zubehör, Hitze, lange Touren, Sitzhöhe","whyNext":"Guter Kontrast für hochpreisige OEM/Aftermarket-Lösungen.","slug":"ducati-multistrada-v4"}'::jsonb,
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    segment = EXCLUDED.segment,
    country_priority = EXCLUDED.country_priority,
    status = EXCLUDED.status,
    guide_path = EXCLUDED.guide_path,
    seat_pain_focus = EXCLUDED.seat_pain_focus,
    why_next = EXCLUDED.why_next,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycles (
    slug, brand, model, segment, country_priority, status, guide_path,
    seat_pain_focus, why_next, source_data, updated_at
  )
  VALUES (
    'honda-nc750x',
    'Honda',
    'Honda NC750X',
    'Alltag / Crossover',
    'Europa',
    'planned',
    NULL,
    'Pendeln, kurze bis mittlere Touren, Budget-Lösungen',
    'Wichtig für günstigere, alltagstaugliche Empfehlungen.',
    '{"name":"Honda NC750X","brand":"Honda","segment":"Alltag / Crossover","countryPriority":"Europa","status":"planned","path":"","seatPainFocus":"Pendeln, kurze bis mittlere Touren, Budget-Lösungen","whyNext":"Wichtig für günstigere, alltagstaugliche Empfehlungen.","slug":"honda-nc750x"}'::jsonb,
    now()
  )
  ON CONFLICT (slug) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    segment = EXCLUDED.segment,
    country_priority = EXCLUDED.country_priority,
    status = EXCLUDED.status,
    guide_path = EXCLUDED.guide_path,
    seat_pain_focus = EXCLUDED.seat_pain_focus,
    why_next = EXCLUDED.why_next,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO solution_paths (
    key, title, summary, best_for, not_ideal_for, cost, confidence, source_data, updated_at
  )
  VALUES (
    'reversible_addon',
    'Reversible Auflage testen',
    '3D-Mesh, Air Cushion oder dünne Komfortauflage testen, bevor die originale Sitzbank verändert wird.',
    'unsichere Ursache, niedriges Budget, schnelle Tests',
    'stark falsche Sitzform oder lange Touren mit klaren Druckpunkten',
    'niedrig bis mittel',
    'MVP: mittel',
    '{"key":"reversible_addon","title":"Reversible Auflage testen","summary":"3D-Mesh, Air Cushion oder dünne Komfortauflage testen, bevor die originale Sitzbank verändert wird.","bestFor":"unsichere Ursache, niedriges Budget, schnelle Tests","notIdealFor":"stark falsche Sitzform oder lange Touren mit klaren Druckpunkten","cost":"niedrig bis mittel","confidence":"MVP: mittel"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    best_for = EXCLUDED.best_for,
    not_ideal_for = EXCLUDED.not_ideal_for,
    cost = EXCLUDED.cost,
    confidence = EXCLUDED.confidence,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO solution_paths (
    key, title, summary, best_for, not_ideal_for, cost, confidence, source_data, updated_at
  )
  VALUES (
    'oem_comfort_seat',
    'OEM Komfort- oder Zubehörsitz prüfen',
    'Suzuki Zubehör kann die sauberste Plug-and-play-Option sein, muss aber mit Sitzhöhe und Rückgabemöglichkeit geprüft werden.',
    'Fahrer, die nicht schneiden oder basteln wollen',
    'wenn die OEM-Form nicht zum Körper passt',
    'mittel bis hoch',
    'MVP: braucht Quellenprüfung',
    '{"key":"oem_comfort_seat","title":"OEM Komfort- oder Zubehörsitz prüfen","summary":"Suzuki Zubehör kann die sauberste Plug-and-play-Option sein, muss aber mit Sitzhöhe und Rückgabemöglichkeit geprüft werden.","bestFor":"Fahrer, die nicht schneiden oder basteln wollen","notIdealFor":"wenn die OEM-Form nicht zum Körper passt","cost":"mittel bis hoch","confidence":"MVP: braucht Quellenprüfung"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    best_for = EXCLUDED.best_for,
    not_ideal_for = EXCLUDED.not_ideal_for,
    cost = EXCLUDED.cost,
    confidence = EXCLUDED.confidence,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO solution_paths (
    key, title, summary, best_for, not_ideal_for, cost, confidence, source_data, updated_at
  )
  VALUES (
    'aftermarket_seat',
    'Aftermarket-Sitz vergleichen',
    'Premiumsitze können auf langen Strecken helfen, sind aber teuer und nicht automatisch für jeden Körper passend.',
    'lange Touren, hohes Budget, klare Rückgaberegeln',
    'kurze sportliche Fahrten oder unklare Beschwerden',
    'hoch',
    'MVP: niedrig bis mittel',
    '{"key":"aftermarket_seat","title":"Aftermarket-Sitz vergleichen","summary":"Premiumsitze können auf langen Strecken helfen, sind aber teuer und nicht automatisch für jeden Körper passend.","bestFor":"lange Touren, hohes Budget, klare Rückgaberegeln","notIdealFor":"kurze sportliche Fahrten oder unklare Beschwerden","cost":"hoch","confidence":"MVP: niedrig bis mittel"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    best_for = EXCLUDED.best_for,
    not_ideal_for = EXCLUDED.not_ideal_for,
    cost = EXCLUDED.cost,
    confidence = EXCLUDED.confidence,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO solution_paths (
    key, title, summary, best_for, not_ideal_for, cost, confidence, source_data, updated_at
  )
  VALUES (
    'professional_upholsterer',
    'Sattler / Sitzbankumbau',
    'Ein guter Sattler kann Form, Breite, Schaum und Bezug gezielt anpassen.',
    'klare Druckpunkte, lange Nutzung des Motorrads, individuelle Anatomie',
    'wenn Rückbau und Originalzustand sehr wichtig sind',
    'mittel bis hoch',
    'MVP: mittel',
    '{"key":"professional_upholsterer","title":"Sattler / Sitzbankumbau","summary":"Ein guter Sattler kann Form, Breite, Schaum und Bezug gezielt anpassen.","bestFor":"klare Druckpunkte, lange Nutzung des Motorrads, individuelle Anatomie","notIdealFor":"wenn Rückbau und Originalzustand sehr wichtig sind","cost":"mittel bis hoch","confidence":"MVP: mittel"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    best_for = EXCLUDED.best_for,
    not_ideal_for = EXCLUDED.not_ideal_for,
    cost = EXCLUDED.cost,
    confidence = EXCLUDED.confidence,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO solution_paths (
    key, title, summary, best_for, not_ideal_for, cost, confidence, source_data, updated_at
  )
  VALUES (
    'diy',
    'DIY nur mit Plan',
    'DIY kann funktionieren, sollte aber mit Dokumentation, Messung und idealerweise einer zweiten Sitzbank starten.',
    'erfahrene Bastler und Lernprojekte',
    'einzige Original-Sitzbank, Zeitdruck oder fehlendes Werkzeug',
    'variabel',
    'MVP: abhängig von Können',
    '{"key":"diy","title":"DIY nur mit Plan","summary":"DIY kann funktionieren, sollte aber mit Dokumentation, Messung und idealerweise einer zweiten Sitzbank starten.","bestFor":"erfahrene Bastler und Lernprojekte","notIdealFor":"einzige Original-Sitzbank, Zeitdruck oder fehlendes Werkzeug","cost":"variabel","confidence":"MVP: abhängig von Können"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    best_for = EXCLUDED.best_for,
    not_ideal_for = EXCLUDED.not_ideal_for,
    cost = EXCLUDED.cost,
    confidence = EXCLUDED.confidence,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO product_categories (
    key, name, problem_solved, limitations, price_band, first_test,
    avoid_when, buying_checks, affiliate_status, source_data, updated_at
  )
  VALUES (
    '3d_mesh_cover',
    '3D-Mesh Sitzauflage',
    'Hitze, Schwitzen, leichte Druckverteilung',
    'erhöht Sitzhöhe leicht und löst keine falsche Sitzform',
    'niedrig',
    'Eine einzelne 60- bis 90-Minuten-Fahrt bei warmem Wetter mit gleicher Hose und gleicher Strecke.',
    'du schon ohne Auflage kaum sicher mit den Füßen auf den Boden kommst.',
    '["passende Größe für die GSX-S1000GX Sitzfläche","sichere Befestigung ohne Rutschen","keine harten Nähte oder Kanten im Sitzbereich","einfache Rückgabe, falls Sitzhöhe oder Gefühl stören"]'::jsonb,
    'affiliate candidate',
    '{"key":"3d_mesh_cover","name":"3D-Mesh Sitzauflage","problemSolved":"Hitze, Schwitzen, leichte Druckverteilung","limitations":"erhöht Sitzhöhe leicht und löst keine falsche Sitzform","priceBand":"niedrig","firstTest":"Eine einzelne 60- bis 90-Minuten-Fahrt bei warmem Wetter mit gleicher Hose und gleicher Strecke.","avoidWhen":"du schon ohne Auflage kaum sicher mit den Füßen auf den Boden kommst.","buyingChecks":["passende Größe für die GSX-S1000GX Sitzfläche","sichere Befestigung ohne Rutschen","keine harten Nähte oder Kanten im Sitzbereich","einfache Rückgabe, falls Sitzhöhe oder Gefühl stören"],"affiliateStatus":"affiliate candidate"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    problem_solved = EXCLUDED.problem_solved,
    limitations = EXCLUDED.limitations,
    price_band = EXCLUDED.price_band,
    first_test = EXCLUDED.first_test,
    avoid_when = EXCLUDED.avoid_when,
    buying_checks = EXCLUDED.buying_checks,
    affiliate_status = EXCLUDED.affiliate_status,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO product_categories (
    key, name, problem_solved, limitations, price_band, first_test,
    avoid_when, buying_checks, affiliate_status, source_data, updated_at
  )
  VALUES (
    'air_cushion',
    'Luftkissen',
    'Druckentlastung auf längeren geraden Strecken',
    'kann entkoppelt wirken und muss sehr niedrig aufgepumpt werden',
    'mittel',
    'Sehr wenig Luft verwenden und erst auf ruhiger Strecke testen, nicht direkt auf einer schnellen Tour.',
    'du sportlich fährst und direkten Kontakt zum Motorrad brauchst.',
    '["Form passt zur Sitzbank und engt nicht an den Oberschenkeln ein","Ventil stört nicht beim Sitzen","Befestigung bleibt beim Auf- und Absteigen stabil","Material ist hitze- und UV-tauglich"]'::jsonb,
    'affiliate candidate',
    '{"key":"air_cushion","name":"Luftkissen","problemSolved":"Druckentlastung auf längeren geraden Strecken","limitations":"kann entkoppelt wirken und muss sehr niedrig aufgepumpt werden","priceBand":"mittel","firstTest":"Sehr wenig Luft verwenden und erst auf ruhiger Strecke testen, nicht direkt auf einer schnellen Tour.","avoidWhen":"du sportlich fährst und direkten Kontakt zum Motorrad brauchst.","buyingChecks":["Form passt zur Sitzbank und engt nicht an den Oberschenkeln ein","Ventil stört nicht beim Sitzen","Befestigung bleibt beim Auf- und Absteigen stabil","Material ist hitze- und UV-tauglich"],"affiliateStatus":"affiliate candidate"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    problem_solved = EXCLUDED.problem_solved,
    limitations = EXCLUDED.limitations,
    price_band = EXCLUDED.price_band,
    first_test = EXCLUDED.first_test,
    avoid_when = EXCLUDED.avoid_when,
    buying_checks = EXCLUDED.buying_checks,
    affiliate_status = EXCLUDED.affiliate_status,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO product_categories (
    key, name, problem_solved, limitations, price_band, first_test,
    avoid_when, buying_checks, affiliate_status, source_data, updated_at
  )
  VALUES (
    'gel_pad',
    'Gel-Pad',
    'kurzfristige Druckminderung für manche Fahrer',
    'kann Hitze speichern und schlechte Form nicht reparieren',
    'niedrig bis mittel',
    'Nur als reversible Auflage testen, bevor Gel in die Sitzbank eingebaut wird.',
    'dein Hauptproblem Hitze, Rutschen oder eine falsche Sitzform ist.',
    '["Dicke und Kantenverlauf prüfen","Temperaturverhalten bei Sonne beachten","Rückgabe möglich halten","nicht als Allheilmittel für Langstrecke betrachten"]'::jsonb,
    'caution',
    '{"key":"gel_pad","name":"Gel-Pad","problemSolved":"kurzfristige Druckminderung für manche Fahrer","limitations":"kann Hitze speichern und schlechte Form nicht reparieren","priceBand":"niedrig bis mittel","firstTest":"Nur als reversible Auflage testen, bevor Gel in die Sitzbank eingebaut wird.","avoidWhen":"dein Hauptproblem Hitze, Rutschen oder eine falsche Sitzform ist.","buyingChecks":["Dicke und Kantenverlauf prüfen","Temperaturverhalten bei Sonne beachten","Rückgabe möglich halten","nicht als Allheilmittel für Langstrecke betrachten"],"affiliateStatus":"caution"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    problem_solved = EXCLUDED.problem_solved,
    limitations = EXCLUDED.limitations,
    price_band = EXCLUDED.price_band,
    first_test = EXCLUDED.first_test,
    avoid_when = EXCLUDED.avoid_when,
    buying_checks = EXCLUDED.buying_checks,
    affiliate_status = EXCLUDED.affiliate_status,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO product_categories (
    key, name, problem_solved, limitations, price_band, first_test,
    avoid_when, buying_checks, affiliate_status, source_data, updated_at
  )
  VALUES (
    'professional_upholstery',
    'Professioneller Sitzbankumbau',
    'Form, Schaum, Breite und Bezug gezielt anpassen',
    'Qualität hängt stark vom Sattler ab, Rückbau nicht immer möglich',
    'mittel bis hoch',
    'Vorher Fotos, Maße, Beschwerden und gewünschte Nutzung dokumentieren.',
    'du noch nicht weißt, ob Druck, Hitze, Rutschen oder Kniewinkel das eigentliche Problem ist.',
    '["Referenzarbeiten und echte Kundenfotos prüfen","Materialaufbau schriftlich klären","Wasserdichtigkeit und Bezug prüfen","Originalsitz oder Zweitsitz als Basis besprechen"]'::jsonb,
    'service listing later',
    '{"key":"professional_upholstery","name":"Professioneller Sitzbankumbau","problemSolved":"Form, Schaum, Breite und Bezug gezielt anpassen","limitations":"Qualität hängt stark vom Sattler ab, Rückbau nicht immer möglich","priceBand":"mittel bis hoch","firstTest":"Vorher Fotos, Maße, Beschwerden und gewünschte Nutzung dokumentieren.","avoidWhen":"du noch nicht weißt, ob Druck, Hitze, Rutschen oder Kniewinkel das eigentliche Problem ist.","buyingChecks":["Referenzarbeiten und echte Kundenfotos prüfen","Materialaufbau schriftlich klären","Wasserdichtigkeit und Bezug prüfen","Originalsitz oder Zweitsitz als Basis besprechen"],"affiliateStatus":"service listing later"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    problem_solved = EXCLUDED.problem_solved,
    limitations = EXCLUDED.limitations,
    price_band = EXCLUDED.price_band,
    first_test = EXCLUDED.first_test,
    avoid_when = EXCLUDED.avoid_when,
    buying_checks = EXCLUDED.buying_checks,
    affiliate_status = EXCLUDED.affiliate_status,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO product_categories (
    key, name, problem_solved, limitations, price_band, first_test,
    avoid_when, buying_checks, affiliate_status, source_data, updated_at
  )
  VALUES (
    'oem_comfort_seat',
    'OEM Komfortsitz',
    'Plug-and-play Lösung ohne eigene Umbauten',
    'passt nicht automatisch zu jedem Körper und kann teuer sein',
    'mittel bis hoch',
    'Nur kaufen, wenn Teilenummer, Modelljahr und Rückgabe eindeutig sind.',
    'du eine stark individuelle Schmerzstelle hast oder die OEM-Form dein Problem ist.',
    '["Teilenummer für Modelljahr prüfen","Sitzhöhe und eventuelle Änderung klären","Rückgabe bei montierter Ware prüfen","Besitzerberichte speziell zur GSX-S1000GX suchen"]'::jsonb,
    'research needed',
    '{"key":"oem_comfort_seat","name":"OEM Komfortsitz","problemSolved":"Plug-and-play Lösung ohne eigene Umbauten","limitations":"passt nicht automatisch zu jedem Körper und kann teuer sein","priceBand":"mittel bis hoch","firstTest":"Nur kaufen, wenn Teilenummer, Modelljahr und Rückgabe eindeutig sind.","avoidWhen":"du eine stark individuelle Schmerzstelle hast oder die OEM-Form dein Problem ist.","buyingChecks":["Teilenummer für Modelljahr prüfen","Sitzhöhe und eventuelle Änderung klären","Rückgabe bei montierter Ware prüfen","Besitzerberichte speziell zur GSX-S1000GX suchen"],"affiliateStatus":"research needed"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    problem_solved = EXCLUDED.problem_solved,
    limitations = EXCLUDED.limitations,
    price_band = EXCLUDED.price_band,
    first_test = EXCLUDED.first_test,
    avoid_when = EXCLUDED.avoid_when,
    buying_checks = EXCLUDED.buying_checks,
    affiliate_status = EXCLUDED.affiliate_status,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO product_categories (
    key, name, problem_solved, limitations, price_band, first_test,
    avoid_when, buying_checks, affiliate_status, source_data, updated_at
  )
  VALUES (
    'aftermarket_seat',
    'Aftermarket Komplettsitz',
    'Langstreckenkomfort, breitere Auflage und definierte Form',
    'hochpreisig, Lieferzeit und Rückgabe können kritisch sein',
    'hoch',
    'Erst kaufen, wenn echte Erfahrungsberichte zum Motorradmodell und Rückgaberegeln passen.',
    'du nur kurze Runden fährst oder unklar ist, woher der Schmerz kommt.',
    '["Lieferland, Zoll und Rückgabe prüfen","Sitzhöhe, Breite und Soziusbereich vergleichen","Bewertungen nach Körpergröße und Fahrtyp filtern","keine Herstellerwerbung mit Erfahrungswerten verwechseln"]'::jsonb,
    'research needed',
    '{"key":"aftermarket_seat","name":"Aftermarket Komplettsitz","problemSolved":"Langstreckenkomfort, breitere Auflage und definierte Form","limitations":"hochpreisig, Lieferzeit und Rückgabe können kritisch sein","priceBand":"hoch","firstTest":"Erst kaufen, wenn echte Erfahrungsberichte zum Motorradmodell und Rückgaberegeln passen.","avoidWhen":"du nur kurze Runden fährst oder unklar ist, woher der Schmerz kommt.","buyingChecks":["Lieferland, Zoll und Rückgabe prüfen","Sitzhöhe, Breite und Soziusbereich vergleichen","Bewertungen nach Körpergröße und Fahrtyp filtern","keine Herstellerwerbung mit Erfahrungswerten verwechseln"],"affiliateStatus":"research needed"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    problem_solved = EXCLUDED.problem_solved,
    limitations = EXCLUDED.limitations,
    price_band = EXCLUDED.price_band,
    first_test = EXCLUDED.first_test,
    avoid_when = EXCLUDED.avoid_when,
    buying_checks = EXCLUDED.buying_checks,
    affiliate_status = EXCLUDED.affiliate_status,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO seat_options (
    key, motorcycle_slug, name, maker, option_type, fitment, market, price_note,
    best_for, watch_out, comfort_logic, research_status, confidence,
    affiliate_status, image_path, image_alt, source_label, source_url, source_data, updated_at
  )
  VALUES (
    'suzuki-premium-seat-de',
    'suzuki-gsx-s1000gx',
    'Suzuki Premium-Sitz Set',
    'Suzuki',
    'OEM comfort seat',
    'GSX-S1000GX, Teilenummer 45100-48820-000 / 45100-48820',
    'Deutschland / Suzuki OEM',
    'Suzuki Deutschland listete 431,55 EUR; Suzuki USA listete 449,95 USD. Vor Kauf lokal erneut prüfen.',
    'Fahrer, die eine plug-and-play Lösung mit OEM-Passform wollen und keine stark individuelle Schmerzstelle haben.',
    'Nicht automatisch die beste Lösung, wenn die originale Sitzform oder Sitzneigung dein Hauptproblem ist.',
    'Zweilagige Urethanschaum-Konstruktion, griffigere Oberflaeche und laut Suzuki geringere Oberflaechentemperatur bei Sonne.',
    'verified source, needs owner feedback',
    4,
    'dealer / affiliate later',
    '/assets/options/comfort-seat.svg',
    'Illustration eines schwarzen Komfort-Motorradsitzes',
    'Suzuki Deutschland',
    'https://motorrad.suzuki.de/modelle/street/gsx-s1000gx/zubehoer/premium-sitz',
    '{"key":"suzuki-premium-seat-de","name":"Suzuki Premium-Sitz Set","maker":"Suzuki","type":"OEM comfort seat","fitment":"GSX-S1000GX, Teilenummer 45100-48820-000 / 45100-48820","market":"Deutschland / Suzuki OEM","priceNote":"Suzuki Deutschland listete 431,55 EUR; Suzuki USA listete 449,95 USD. Vor Kauf lokal erneut prüfen.","bestFor":"Fahrer, die eine plug-and-play Lösung mit OEM-Passform wollen und keine stark individuelle Schmerzstelle haben.","watchOut":"Nicht automatisch die beste Lösung, wenn die originale Sitzform oder Sitzneigung dein Hauptproblem ist.","comfortLogic":"Zweilagige Urethanschaum-Konstruktion, griffigere Oberflaeche und laut Suzuki geringere Oberflaechentemperatur bei Sonne.","researchStatus":"verified source, needs owner feedback","confidence":4,"affiliateStatus":"dealer / affiliate later","imagePath":"/assets/options/comfort-seat.svg","imageAlt":"Illustration eines schwarzen Komfort-Motorradsitzes","sourceLabel":"Suzuki Deutschland","sourceUrl":"https://motorrad.suzuki.de/modelle/street/gsx-s1000gx/zubehoer/premium-sitz"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    motorcycle_slug = EXCLUDED.motorcycle_slug,
    name = EXCLUDED.name,
    maker = EXCLUDED.maker,
    option_type = EXCLUDED.option_type,
    fitment = EXCLUDED.fitment,
    market = EXCLUDED.market,
    price_note = EXCLUDED.price_note,
    best_for = EXCLUDED.best_for,
    watch_out = EXCLUDED.watch_out,
    comfort_logic = EXCLUDED.comfort_logic,
    research_status = EXCLUDED.research_status,
    confidence = EXCLUDED.confidence,
    affiliate_status = EXCLUDED.affiliate_status,
    image_path = EXCLUDED.image_path,
    image_alt = EXCLUDED.image_alt,
    source_label = EXCLUDED.source_label,
    source_url = EXCLUDED.source_url,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO seat_options (
    key, motorcycle_slug, name, maker, option_type, fitment, market, price_note,
    best_for, watch_out, comfort_logic, research_status, confidence,
    affiliate_status, image_path, image_alt, source_label, source_url, source_data, updated_at
  )
  VALUES (
    'sargent-world-sport-front',
    'suzuki-gsx-s1000gx',
    'Sargent World Sport Front Seat',
    'Sargent',
    'aftermarket front seat',
    'GSX-S1000GX 2024+ laut Sargent Produktseiten',
    'USA / UK Import möglich',
    'US-Listenpreise für Front-Sitz lagen je nach Variante um 429,95 bis 639,95 USD; UK-Import kann Zoll, Versand und Rückgabe verändern.',
    'Tourenfahrer mit Budget, die eine breitere definierte Sitzform und einen Komplettsitz statt Auflage suchen.',
    'Teuer, Rückgabe/Restocking Fee, Lieferzeit und Importkosten vorher klären. Für kurze Runden oft überdimensioniert.',
    'Sargent nennt breiteren Sitzpan, Performance-Plus/DTX Varianten und optionale Heizung je nach Ausfuehrung.',
    'verified source, needs EU fitment and return check',
    3,
    'research affiliate later',
    '/assets/options/comfort-seat.svg',
    'Illustration eines breiteren Touring-Motorradsitzes',
    'Sargent Cycle',
    'https://www.sargentcycle.com/seats/suzuki/gsxs1000/gsxs1000gx?order=relevance%3Adesc&show=24',
    '{"key":"sargent-world-sport-front","name":"Sargent World Sport Front Seat","maker":"Sargent","type":"aftermarket front seat","fitment":"GSX-S1000GX 2024+ laut Sargent Produktseiten","market":"USA / UK Import möglich","priceNote":"US-Listenpreise für Front-Sitz lagen je nach Variante um 429,95 bis 639,95 USD; UK-Import kann Zoll, Versand und Rückgabe verändern.","bestFor":"Tourenfahrer mit Budget, die eine breitere definierte Sitzform und einen Komplettsitz statt Auflage suchen.","watchOut":"Teuer, Rückgabe/Restocking Fee, Lieferzeit und Importkosten vorher klären. Für kurze Runden oft überdimensioniert.","comfortLogic":"Sargent nennt breiteren Sitzpan, Performance-Plus/DTX Varianten und optionale Heizung je nach Ausfuehrung.","researchStatus":"verified source, needs EU fitment and return check","confidence":3,"affiliateStatus":"research affiliate later","imagePath":"/assets/options/comfort-seat.svg","imageAlt":"Illustration eines breiteren Touring-Motorradsitzes","sourceLabel":"Sargent Cycle","sourceUrl":"https://www.sargentcycle.com/seats/suzuki/gsxs1000/gsxs1000gx?order=relevance%3Adesc&show=24"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    motorcycle_slug = EXCLUDED.motorcycle_slug,
    name = EXCLUDED.name,
    maker = EXCLUDED.maker,
    option_type = EXCLUDED.option_type,
    fitment = EXCLUDED.fitment,
    market = EXCLUDED.market,
    price_note = EXCLUDED.price_note,
    best_for = EXCLUDED.best_for,
    watch_out = EXCLUDED.watch_out,
    comfort_logic = EXCLUDED.comfort_logic,
    research_status = EXCLUDED.research_status,
    confidence = EXCLUDED.confidence,
    affiliate_status = EXCLUDED.affiliate_status,
    image_path = EXCLUDED.image_path,
    image_alt = EXCLUDED.image_alt,
    source_label = EXCLUDED.source_label,
    source_url = EXCLUDED.source_url,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO seat_options (
    key, motorcycle_slug, name, maker, option_type, fitment, market, price_note,
    best_for, watch_out, comfort_logic, research_status, confidence,
    affiliate_status, image_path, image_alt, source_label, source_url, source_data, updated_at
  )
  VALUES (
    '3d-mesh-first-test',
    'suzuki-gsx-s1000gx',
    '3D-Mesh Auflage als erster Test',
    'Generic / mehrere Anbieter',
    'reversible add-on',
    'Größe und Befestigung müssen zur GSX-S1000GX Sitzfläche passen',
    'Amazon, Motorradshops, Direktanbieter',
    'Niedrige bis mittlere Kosten; konkrete Links erst nach Affiliate- und Qualitätsprüfung.',
    'Hitze, Schwitzen, leichtes Druckgefühl und alle, die vor einem teuren Sitz erst etwas Rückbaubares testen wollen.',
    'Erhöht die Sitzhöhe leicht, kann rutschen und löst keine falsche Sitzform.',
    'Mehr Luftzirkulation zwischen Hose und Sitz; sinnvoll vor allem bei warmem Wetter und längeren Etappen.',
    'category validated, product shortlist needed',
    3,
    'strong affiliate candidate',
    '/assets/options/mesh-pad.svg',
    'Illustration einer 3D-Mesh Motorrad-Sitzauflage',
    'Forum and category research',
    'https://www.gsxs1000.org/threads/gx-seat-options.48928/',
    '{"key":"3d-mesh-first-test","name":"3D-Mesh Auflage als erster Test","maker":"Generic / mehrere Anbieter","type":"reversible add-on","fitment":"Größe und Befestigung müssen zur GSX-S1000GX Sitzfläche passen","market":"Amazon, Motorradshops, Direktanbieter","priceNote":"Niedrige bis mittlere Kosten; konkrete Links erst nach Affiliate- und Qualitätsprüfung.","bestFor":"Hitze, Schwitzen, leichtes Druckgefühl und alle, die vor einem teuren Sitz erst etwas Rückbaubares testen wollen.","watchOut":"Erhöht die Sitzhöhe leicht, kann rutschen und löst keine falsche Sitzform.","comfortLogic":"Mehr Luftzirkulation zwischen Hose und Sitz; sinnvoll vor allem bei warmem Wetter und längeren Etappen.","researchStatus":"category validated, product shortlist needed","confidence":3,"affiliateStatus":"strong affiliate candidate","imagePath":"/assets/options/mesh-pad.svg","imageAlt":"Illustration einer 3D-Mesh Motorrad-Sitzauflage","sourceLabel":"Forum and category research","sourceUrl":"https://www.gsxs1000.org/threads/gx-seat-options.48928/"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    motorcycle_slug = EXCLUDED.motorcycle_slug,
    name = EXCLUDED.name,
    maker = EXCLUDED.maker,
    option_type = EXCLUDED.option_type,
    fitment = EXCLUDED.fitment,
    market = EXCLUDED.market,
    price_note = EXCLUDED.price_note,
    best_for = EXCLUDED.best_for,
    watch_out = EXCLUDED.watch_out,
    comfort_logic = EXCLUDED.comfort_logic,
    research_status = EXCLUDED.research_status,
    confidence = EXCLUDED.confidence,
    affiliate_status = EXCLUDED.affiliate_status,
    image_path = EXCLUDED.image_path,
    image_alt = EXCLUDED.image_alt,
    source_label = EXCLUDED.source_label,
    source_url = EXCLUDED.source_url,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO seat_options (
    key, motorcycle_slug, name, maker, option_type, fitment, market, price_note,
    best_for, watch_out, comfort_logic, research_status, confidence,
    affiliate_status, image_path, image_alt, source_label, source_url, source_data, updated_at
  )
  VALUES (
    'local-upholstery-custom',
    'suzuki-gsx-s1000gx',
    'Lokaler Sattler / Sitzbankumbau',
    'Regionaler Sattler',
    'custom upholstery',
    'Originalsitz oder Zweitsitz als Basis',
    'Deutschland / DACH lokal',
    'Preis stark abhaengig von Schaumaufbau, Bezug, Naehten, Heizung und Abdichtung.',
    'Klare Schmerzstelle, spezieller Körperbau, Wunsch nach anderer Form, Höhe oder Bezug.',
    'Qualität variiert stark. Fotos, Materialaufbau, Wasserdichtigkeit und Rückbau vorher schriftlich klären.',
    'Form, Breite, Kanten, Schaumhaerte und Bezug koennen gezielt an den Fahrer angepasst werden.',
    'needs local provider database',
    2,
    'service directory later',
    '/assets/options/upholstery-workshop.svg',
    'Illustration einer Sitzbank im Sattler-Workshop',
    'Moto Seat Lab research backlog',
    '/de/diy/',
    '{"key":"local-upholstery-custom","name":"Lokaler Sattler / Sitzbankumbau","maker":"Regionaler Sattler","type":"custom upholstery","fitment":"Originalsitz oder Zweitsitz als Basis","market":"Deutschland / DACH lokal","priceNote":"Preis stark abhaengig von Schaumaufbau, Bezug, Naehten, Heizung und Abdichtung.","bestFor":"Klare Schmerzstelle, spezieller Körperbau, Wunsch nach anderer Form, Höhe oder Bezug.","watchOut":"Qualität variiert stark. Fotos, Materialaufbau, Wasserdichtigkeit und Rückbau vorher schriftlich klären.","comfortLogic":"Form, Breite, Kanten, Schaumhaerte und Bezug koennen gezielt an den Fahrer angepasst werden.","researchStatus":"needs local provider database","confidence":2,"affiliateStatus":"service directory later","imagePath":"/assets/options/upholstery-workshop.svg","imageAlt":"Illustration einer Sitzbank im Sattler-Workshop","sourceLabel":"Moto Seat Lab research backlog","sourceUrl":"/de/diy/"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    motorcycle_slug = EXCLUDED.motorcycle_slug,
    name = EXCLUDED.name,
    maker = EXCLUDED.maker,
    option_type = EXCLUDED.option_type,
    fitment = EXCLUDED.fitment,
    market = EXCLUDED.market,
    price_note = EXCLUDED.price_note,
    best_for = EXCLUDED.best_for,
    watch_out = EXCLUDED.watch_out,
    comfort_logic = EXCLUDED.comfort_logic,
    research_status = EXCLUDED.research_status,
    confidence = EXCLUDED.confidence,
    affiliate_status = EXCLUDED.affiliate_status,
    image_path = EXCLUDED.image_path,
    image_alt = EXCLUDED.image_alt,
    source_label = EXCLUDED.source_label,
    source_url = EXCLUDED.source_url,
    source_data = EXCLUDED.source_data,
    updated_at = now();
DELETE FROM research_sources WHERE motorcycle_slug = 'suzuki-gsx-s1000gx';
INSERT INTO research_sources (
    motorcycle_slug, title, url, notes, confidence, source_data, updated_at
  )
  VALUES (
    'suzuki-gsx-s1000gx',
    'Suzuki Global GSX-S1000GX',
    'https://www.globalsuzuki.com/motorcycle/smgs/products/2024gsx-s1000gx/',
    'Official model source. Seat accessory details need separate verification.',
    5,
    '{"title":"Suzuki Global GSX-S1000GX","url":"https://www.globalsuzuki.com/motorcycle/smgs/products/2024gsx-s1000gx/","type":"manufacturer_official","confidence":5,"notes":"Official model source. Seat accessory details need separate verification."}'::jsonb,
    now()
  );
INSERT INTO research_sources (
    motorcycle_slug, title, url, notes, confidence, source_data, updated_at
  )
  VALUES (
    'suzuki-gsx-s1000gx',
    'Suzuki USA GSX-S1000GX accessory catalog',
    'https://store.suzukicycles.com/c/accessories_standard_gsx-s1000gx',
    'Useful for accessory naming and availability; Germany availability must be verified separately.',
    4,
    '{"title":"Suzuki USA GSX-S1000GX accessory catalog","url":"https://store.suzukicycles.com/c/accessories_standard_gsx-s1000gx","type":"manufacturer_accessory_catalog","confidence":4,"notes":"Useful for accessory naming and availability; Germany availability must be verified separately."}'::jsonb,
    now()
  );
INSERT INTO research_sources (
    motorcycle_slug, title, url, notes, confidence, source_data, updated_at
  )
  VALUES (
    'suzuki-gsx-s1000gx',
    'Global forum seat pain research',
    'https://github.com/sokolicek/moto-seat-lab/blob/main/docs/research/global-forum-seat-pain-research.md',
    'Anecdotal pain-point research, not product proof.',
    2,
    '{"title":"Global forum seat pain research","url":"https://github.com/sokolicek/moto-seat-lab/blob/main/docs/research/global-forum-seat-pain-research.md","type":"research_note","confidence":2,"notes":"Anecdotal pain-point research, not product proof."}'::jsonb,
    now()
  );
INSERT INTO motorcycle_technical_profiles (
    motorcycle_slug, seat_height_mm, wet_weight_kg, riding_triangle_status,
    usage_profile, seat_comfort_risks, required_measurements, notes, source_data, updated_at
  )
  VALUES (
    'suzuki-gsx-s1000gx',
    NULL,
    NULL,
    'research_needed',
    '["sport_touring","country_road","highway","weekend_touring"]'::jsonb,
    '["pressure_after_60_min","heat","forward_slide","knee_angle"]'::jsonb,
    '["seat_height_mm","usable_seat_width_sitbone_zone_mm","seat_pan_slope_deg","footpeg_to_seat_vertical_mm","handlebar_reach_mm"]'::jsonb,
    'Active pilot model. Official and measured values still need verification before numeric calculations.',
    '{"motorcycleSlug":"suzuki-gsx-s1000gx","seatHeightMm":null,"wetWeightKg":null,"ridingTriangleStatus":"research_needed","usageProfile":["sport_touring","country_road","highway","weekend_touring"],"seatComfortRisks":["pressure_after_60_min","heat","forward_slide","knee_angle"],"requiredMeasurements":["seat_height_mm","usable_seat_width_sitbone_zone_mm","seat_pan_slope_deg","footpeg_to_seat_vertical_mm","handlebar_reach_mm"],"notes":"Active pilot model. Official and measured values still need verification before numeric calculations."}'::jsonb,
    now()
  )
  ON CONFLICT (motorcycle_slug) DO UPDATE SET
    seat_height_mm = EXCLUDED.seat_height_mm,
    wet_weight_kg = EXCLUDED.wet_weight_kg,
    riding_triangle_status = EXCLUDED.riding_triangle_status,
    usage_profile = EXCLUDED.usage_profile,
    seat_comfort_risks = EXCLUDED.seat_comfort_risks,
    required_measurements = EXCLUDED.required_measurements,
    notes = EXCLUDED.notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycle_technical_profiles (
    motorcycle_slug, seat_height_mm, wet_weight_kg, riding_triangle_status,
    usage_profile, seat_comfort_risks, required_measurements, notes, source_data, updated_at
  )
  VALUES (
    'bmw-r-1300-gs',
    NULL,
    NULL,
    'research_needed',
    '["adventure_touring","two_up","long_distance"]'::jsonb,
    '["seat_height","long_distance_pressure","passenger_comfort"]'::jsonb,
    '["seat_height_mm","seat_width_mm","handlebar_reach_mm","footpeg_position_mm"]'::jsonb,
    'High-priority DACH model for future verified guide.',
    '{"motorcycleSlug":"bmw-r-1300-gs","seatHeightMm":null,"wetWeightKg":null,"ridingTriangleStatus":"research_needed","usageProfile":["adventure_touring","two_up","long_distance"],"seatComfortRisks":["seat_height","long_distance_pressure","passenger_comfort"],"requiredMeasurements":["seat_height_mm","seat_width_mm","handlebar_reach_mm","footpeg_position_mm"],"notes":"High-priority DACH model for future verified guide."}'::jsonb,
    now()
  )
  ON CONFLICT (motorcycle_slug) DO UPDATE SET
    seat_height_mm = EXCLUDED.seat_height_mm,
    wet_weight_kg = EXCLUDED.wet_weight_kg,
    riding_triangle_status = EXCLUDED.riding_triangle_status,
    usage_profile = EXCLUDED.usage_profile,
    seat_comfort_risks = EXCLUDED.seat_comfort_risks,
    required_measurements = EXCLUDED.required_measurements,
    notes = EXCLUDED.notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycle_technical_profiles (
    motorcycle_slug, seat_height_mm, wet_weight_kg, riding_triangle_status,
    usage_profile, seat_comfort_risks, required_measurements, notes, source_data, updated_at
  )
  VALUES (
    'bmw-r-1250-gs',
    NULL,
    NULL,
    'research_needed',
    '["adventure_touring","used_market","two_up"]'::jsonb,
    '["seat_height","accessory_choice_overload","long_distance_pressure"]'::jsonb,
    '["seat_height_mm","seat_width_mm","seat_options_oem_aftermarket"]'::jsonb,
    'Large used market and many seat variants.',
    '{"motorcycleSlug":"bmw-r-1250-gs","seatHeightMm":null,"wetWeightKg":null,"ridingTriangleStatus":"research_needed","usageProfile":["adventure_touring","used_market","two_up"],"seatComfortRisks":["seat_height","accessory_choice_overload","long_distance_pressure"],"requiredMeasurements":["seat_height_mm","seat_width_mm","seat_options_oem_aftermarket"],"notes":"Large used market and many seat variants."}'::jsonb,
    now()
  )
  ON CONFLICT (motorcycle_slug) DO UPDATE SET
    seat_height_mm = EXCLUDED.seat_height_mm,
    wet_weight_kg = EXCLUDED.wet_weight_kg,
    riding_triangle_status = EXCLUDED.riding_triangle_status,
    usage_profile = EXCLUDED.usage_profile,
    seat_comfort_risks = EXCLUDED.seat_comfort_risks,
    required_measurements = EXCLUDED.required_measurements,
    notes = EXCLUDED.notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycle_technical_profiles (
    motorcycle_slug, seat_height_mm, wet_weight_kg, riding_triangle_status,
    usage_profile, seat_comfort_risks, required_measurements, notes, source_data, updated_at
  )
  VALUES (
    'yamaha-tracer-9-9-gt',
    NULL,
    NULL,
    'research_needed',
    '["sport_touring","weekend_touring","country_road"]'::jsonb,
    '["forward_slide","touring_pressure","wind_pressure"]'::jsonb,
    '["seat_slope_deg","seat_height_mm","wind_pressure_notes"]'::jsonb,
    'Useful comparison class for GSX-S1000GX.',
    '{"motorcycleSlug":"yamaha-tracer-9-9-gt","seatHeightMm":null,"wetWeightKg":null,"ridingTriangleStatus":"research_needed","usageProfile":["sport_touring","weekend_touring","country_road"],"seatComfortRisks":["forward_slide","touring_pressure","wind_pressure"],"requiredMeasurements":["seat_slope_deg","seat_height_mm","wind_pressure_notes"],"notes":"Useful comparison class for GSX-S1000GX."}'::jsonb,
    now()
  )
  ON CONFLICT (motorcycle_slug) DO UPDATE SET
    seat_height_mm = EXCLUDED.seat_height_mm,
    wet_weight_kg = EXCLUDED.wet_weight_kg,
    riding_triangle_status = EXCLUDED.riding_triangle_status,
    usage_profile = EXCLUDED.usage_profile,
    seat_comfort_risks = EXCLUDED.seat_comfort_risks,
    required_measurements = EXCLUDED.required_measurements,
    notes = EXCLUDED.notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO motorcycle_technical_profiles (
    motorcycle_slug, seat_height_mm, wet_weight_kg, riding_triangle_status,
    usage_profile, seat_comfort_risks, required_measurements, notes, source_data, updated_at
  )
  VALUES (
    'honda-crf1100l-africa-twin',
    NULL,
    NULL,
    'research_needed',
    '["adventure","travel","light_offroad"]'::jsonb,
    '["seat_height","standing_transition","long_distance_pressure"]'::jsonb,
    '["low_high_seat_positions","standing_clearance","seat_width_mm"]'::jsonb,
    'Adventure/offroad movement changes seat requirements.',
    '{"motorcycleSlug":"honda-crf1100l-africa-twin","seatHeightMm":null,"wetWeightKg":null,"ridingTriangleStatus":"research_needed","usageProfile":["adventure","travel","light_offroad"],"seatComfortRisks":["seat_height","standing_transition","long_distance_pressure"],"requiredMeasurements":["low_high_seat_positions","standing_clearance","seat_width_mm"],"notes":"Adventure/offroad movement changes seat requirements."}'::jsonb,
    now()
  )
  ON CONFLICT (motorcycle_slug) DO UPDATE SET
    seat_height_mm = EXCLUDED.seat_height_mm,
    wet_weight_kg = EXCLUDED.wet_weight_kg,
    riding_triangle_status = EXCLUDED.riding_triangle_status,
    usage_profile = EXCLUDED.usage_profile,
    seat_comfort_risks = EXCLUDED.seat_comfort_risks,
    required_measurements = EXCLUDED.required_measurements,
    notes = EXCLUDED.notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO seat_materials (
    key, name, material_type, comfort_role, best_for, avoid_when,
    skill_level, price_band, durability_notes, research_status, source_data, updated_at
  )
  VALUES (
    '3d_mesh_spacer_fabric',
    '3D-Mesh / Abstandsgestrick',
    'cover_addon',
    'Luftzirkulation, Feuchtigkeitsabstand, leichter Druckausgleich',
    'Sommer, Stadt, Touren bei Hitze, reversible Tests vor teuren Umbauten',
    'Sitzhöhe ist bereits kritisch oder die Auflage rutscht auf dem Bezug',
    'beginner',
    'low_to_medium',
    'Abhängig von Befestigung, UV-Belastung und Kantenverarbeitung.',
    'category_validated',
    '{"key":"3d_mesh_spacer_fabric","name":"3D-Mesh / Abstandsgestrick","materialType":"cover_addon","comfortRole":"Luftzirkulation, Feuchtigkeitsabstand, leichter Druckausgleich","bestFor":"Sommer, Stadt, Touren bei Hitze, reversible Tests vor teuren Umbauten","avoidWhen":"Sitzhöhe ist bereits kritisch oder die Auflage rutscht auf dem Bezug","skillLevel":"beginner","priceBand":"low_to_medium","durabilityNotes":"Abhängig von Befestigung, UV-Belastung und Kantenverarbeitung.","researchStatus":"category_validated"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    material_type = EXCLUDED.material_type,
    comfort_role = EXCLUDED.comfort_role,
    best_for = EXCLUDED.best_for,
    avoid_when = EXCLUDED.avoid_when,
    skill_level = EXCLUDED.skill_level,
    price_band = EXCLUDED.price_band,
    durability_notes = EXCLUDED.durability_notes,
    research_status = EXCLUDED.research_status,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO seat_materials (
    key, name, material_type, comfort_role, best_for, avoid_when,
    skill_level, price_band, durability_notes, research_status, source_data, updated_at
  )
  VALUES (
    'gel_insert',
    'Gel-Einlage',
    'insert',
    'kurzfristige Druckverteilung für manche Fahrer',
    'gezielte Druckminderung, wenn Hitze nicht das Hauptproblem ist',
    'Sommerhitze, zu weicher Serienschaum, falsche Sitzform',
    'intermediate',
    'low_to_medium',
    'Kanten, Dicke und Temperaturverhalten vor Einbau testen.',
    'needs_product_testing',
    '{"key":"gel_insert","name":"Gel-Einlage","materialType":"insert","comfortRole":"kurzfristige Druckverteilung für manche Fahrer","bestFor":"gezielte Druckminderung, wenn Hitze nicht das Hauptproblem ist","avoidWhen":"Sommerhitze, zu weicher Serienschaum, falsche Sitzform","skillLevel":"intermediate","priceBand":"low_to_medium","durabilityNotes":"Kanten, Dicke und Temperaturverhalten vor Einbau testen.","researchStatus":"needs_product_testing"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    material_type = EXCLUDED.material_type,
    comfort_role = EXCLUDED.comfort_role,
    best_for = EXCLUDED.best_for,
    avoid_when = EXCLUDED.avoid_when,
    skill_level = EXCLUDED.skill_level,
    price_band = EXCLUDED.price_band,
    durability_notes = EXCLUDED.durability_notes,
    research_status = EXCLUDED.research_status,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO seat_materials (
    key, name, material_type, comfort_role, best_for, avoid_when,
    skill_level, price_band, durability_notes, research_status, source_data, updated_at
  )
  VALUES (
    'pu_comfort_foam',
    'PU-Komfortschaum',
    'foam',
    'Basis-Komfortlage, Formkorrektur, Druckverteilung',
    'Sattlerumbau, gezielte Formänderung, längere Nutzung',
    'ohne Messung einfach nur weicher gemacht werden soll',
    'professional',
    'medium',
    'Dichte, Härte und Aufbau müssen zum Fahrergewicht passen.',
    'needs_specification',
    '{"key":"pu_comfort_foam","name":"PU-Komfortschaum","materialType":"foam","comfortRole":"Basis-Komfortlage, Formkorrektur, Druckverteilung","bestFor":"Sattlerumbau, gezielte Formänderung, längere Nutzung","avoidWhen":"ohne Messung einfach nur weicher gemacht werden soll","skillLevel":"professional","priceBand":"medium","durabilityNotes":"Dichte, Härte und Aufbau müssen zum Fahrergewicht passen.","researchStatus":"needs_specification"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    material_type = EXCLUDED.material_type,
    comfort_role = EXCLUDED.comfort_role,
    best_for = EXCLUDED.best_for,
    avoid_when = EXCLUDED.avoid_when,
    skill_level = EXCLUDED.skill_level,
    price_band = EXCLUDED.price_band,
    durability_notes = EXCLUDED.durability_notes,
    research_status = EXCLUDED.research_status,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO seat_materials (
    key, name, material_type, comfort_role, best_for, avoid_when,
    skill_level, price_band, durability_notes, research_status, source_data, updated_at
  )
  VALUES (
    'memory_foam',
    'Visco-/Memory-Schaum',
    'foam',
    'Anpassung an Körperform, weicheres Sitzgefühl',
    'kurze bis mittlere Touren, wenn Einsinken kontrolliert bleibt',
    'Hitze, sportliches Fahren oder wenn direkter Kontakt nötig ist',
    'professional',
    'medium',
    'Temperaturabhängig; kann im Sommer anders wirken als im Frühjahr.',
    'needs_testing',
    '{"key":"memory_foam","name":"Visco-/Memory-Schaum","materialType":"foam","comfortRole":"Anpassung an Körperform, weicheres Sitzgefühl","bestFor":"kurze bis mittlere Touren, wenn Einsinken kontrolliert bleibt","avoidWhen":"Hitze, sportliches Fahren oder wenn direkter Kontakt nötig ist","skillLevel":"professional","priceBand":"medium","durabilityNotes":"Temperaturabhängig; kann im Sommer anders wirken als im Frühjahr.","researchStatus":"needs_testing"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    material_type = EXCLUDED.material_type,
    comfort_role = EXCLUDED.comfort_role,
    best_for = EXCLUDED.best_for,
    avoid_when = EXCLUDED.avoid_when,
    skill_level = EXCLUDED.skill_level,
    price_band = EXCLUDED.price_band,
    durability_notes = EXCLUDED.durability_notes,
    research_status = EXCLUDED.research_status,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO seat_materials (
    key, name, material_type, comfort_role, best_for, avoid_when,
    skill_level, price_band, durability_notes, research_status, source_data, updated_at
  )
  VALUES (
    'anti_slip_cover',
    'Rutschhemmender Bezug',
    'cover',
    'weniger Vorrutschen, stabilere Sitzposition',
    'Rutschen nach vorne, sportliches Touring, häufiges Bremsen',
    'zu viel Bewegungsfreiheit auf Landstraße gebraucht wird',
    'professional',
    'medium',
    'Abrieb, Wasseraufnahme, Nähte und Reinigung prüfen.',
    'needs_supplier_data',
    '{"key":"anti_slip_cover","name":"Rutschhemmender Bezug","materialType":"cover","comfortRole":"weniger Vorrutschen, stabilere Sitzposition","bestFor":"Rutschen nach vorne, sportliches Touring, häufiges Bremsen","avoidWhen":"zu viel Bewegungsfreiheit auf Landstraße gebraucht wird","skillLevel":"professional","priceBand":"medium","durabilityNotes":"Abrieb, Wasseraufnahme, Nähte und Reinigung prüfen.","researchStatus":"needs_supplier_data"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    material_type = EXCLUDED.material_type,
    comfort_role = EXCLUDED.comfort_role,
    best_for = EXCLUDED.best_for,
    avoid_when = EXCLUDED.avoid_when,
    skill_level = EXCLUDED.skill_level,
    price_band = EXCLUDED.price_band,
    durability_notes = EXCLUDED.durability_notes,
    research_status = EXCLUDED.research_status,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO seat_materials (
    key, name, material_type, comfort_role, best_for, avoid_when,
    skill_level, price_band, durability_notes, research_status, source_data, updated_at
  )
  VALUES (
    'seat_heating_pad',
    'Sitzheizungs-Matte',
    'electrical',
    'Winterkomfort, Temperaturstabilität',
    'kalte Länder, Pendeln, lange Touren im Frühjahr/Herbst',
    'keine saubere elektrische Absicherung und Abdichtung möglich ist',
    'professional',
    'medium_to_high',
    'Elektrik, Wasserdichtigkeit und Garantie immer vorab klären.',
    'needs_safety_review',
    '{"key":"seat_heating_pad","name":"Sitzheizungs-Matte","materialType":"electrical","comfortRole":"Winterkomfort, Temperaturstabilität","bestFor":"kalte Länder, Pendeln, lange Touren im Frühjahr/Herbst","avoidWhen":"keine saubere elektrische Absicherung und Abdichtung möglich ist","skillLevel":"professional","priceBand":"medium_to_high","durabilityNotes":"Elektrik, Wasserdichtigkeit und Garantie immer vorab klären.","researchStatus":"needs_safety_review"}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    material_type = EXCLUDED.material_type,
    comfort_role = EXCLUDED.comfort_role,
    best_for = EXCLUDED.best_for,
    avoid_when = EXCLUDED.avoid_when,
    skill_level = EXCLUDED.skill_level,
    price_band = EXCLUDED.price_band,
    durability_notes = EXCLUDED.durability_notes,
    research_status = EXCLUDED.research_status,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO workshop_tools (
    key, name, tool_type, skill_level, used_for, risk_notes, buying_notes, source_data, updated_at
  )
  VALUES (
    'staple_remover',
    'Klammerentferner',
    'disassembly',
    'beginner',
    'alte Bezugsklammern sauber entfernen',
    'Sitzwanne nicht beschädigen, Schutzbrille verwenden.',
    'Stabiler Griff und flache Spitze sind wichtiger als ein billiges Set.',
    '{"key":"staple_remover","name":"Klammerentferner","toolType":"disassembly","skillLevel":"beginner","usedFor":"alte Bezugsklammern sauber entfernen","riskNotes":"Sitzwanne nicht beschädigen, Schutzbrille verwenden.","buyingNotes":"Stabiler Griff und flache Spitze sind wichtiger als ein billiges Set."}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    tool_type = EXCLUDED.tool_type,
    skill_level = EXCLUDED.skill_level,
    used_for = EXCLUDED.used_for,
    risk_notes = EXCLUDED.risk_notes,
    buying_notes = EXCLUDED.buying_notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO workshop_tools (
    key, name, tool_type, skill_level, used_for, risk_notes, buying_notes, source_data, updated_at
  )
  VALUES (
    'electric_stapler',
    'Elektro- oder Drucklufttacker',
    'assembly',
    'intermediate',
    'Bezug wieder an der Sitzwanne befestigen',
    'Zu lange Klammern können Sitzwanne oder Bezug beschädigen.',
    'Vorher Klammerlänge und Material der Sitzwanne prüfen.',
    '{"key":"electric_stapler","name":"Elektro- oder Drucklufttacker","toolType":"assembly","skillLevel":"intermediate","usedFor":"Bezug wieder an der Sitzwanne befestigen","riskNotes":"Zu lange Klammern können Sitzwanne oder Bezug beschädigen.","buyingNotes":"Vorher Klammerlänge und Material der Sitzwanne prüfen."}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    tool_type = EXCLUDED.tool_type,
    skill_level = EXCLUDED.skill_level,
    used_for = EXCLUDED.used_for,
    risk_notes = EXCLUDED.risk_notes,
    buying_notes = EXCLUDED.buying_notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO workshop_tools (
    key, name, tool_type, skill_level, used_for, risk_notes, buying_notes, source_data, updated_at
  )
  VALUES (
    'foam_knife',
    'Schaummesser / elektrisches Messer',
    'foam_shaping',
    'intermediate',
    'Schaum grob schneiden und Übergänge formen',
    'Zu viel Material ist schnell weg; immer in kleinen Schritten arbeiten.',
    'Erst an Reststücken üben.',
    '{"key":"foam_knife","name":"Schaummesser / elektrisches Messer","toolType":"foam_shaping","skillLevel":"intermediate","usedFor":"Schaum grob schneiden und Übergänge formen","riskNotes":"Zu viel Material ist schnell weg; immer in kleinen Schritten arbeiten.","buyingNotes":"Erst an Reststücken üben."}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    tool_type = EXCLUDED.tool_type,
    skill_level = EXCLUDED.skill_level,
    used_for = EXCLUDED.used_for,
    risk_notes = EXCLUDED.risk_notes,
    buying_notes = EXCLUDED.buying_notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO workshop_tools (
    key, name, tool_type, skill_level, used_for, risk_notes, buying_notes, source_data, updated_at
  )
  VALUES (
    'spray_adhesive',
    'Kontakt- oder Sprühkleber',
    'adhesive',
    'intermediate',
    'Schaumlagen und Bezugshilfen fixieren',
    'Lüftung, Temperatur, Ablüftzeit und Materialverträglichkeit beachten.',
    'Nur Kleber verwenden, der für Schaum und Bezugsmaterial geeignet ist.',
    '{"key":"spray_adhesive","name":"Kontakt- oder Sprühkleber","toolType":"adhesive","skillLevel":"intermediate","usedFor":"Schaumlagen und Bezugshilfen fixieren","riskNotes":"Lüftung, Temperatur, Ablüftzeit und Materialverträglichkeit beachten.","buyingNotes":"Nur Kleber verwenden, der für Schaum und Bezugsmaterial geeignet ist."}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    tool_type = EXCLUDED.tool_type,
    skill_level = EXCLUDED.skill_level,
    used_for = EXCLUDED.used_for,
    risk_notes = EXCLUDED.risk_notes,
    buying_notes = EXCLUDED.buying_notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO workshop_tools (
    key, name, tool_type, skill_level, used_for, risk_notes, buying_notes, source_data, updated_at
  )
  VALUES (
    'measuring_tape_marker',
    'Maßband und Markierstift',
    'measurement',
    'beginner',
    'Sitzbreite, Kanten, Schmerzpunkte und Änderungen dokumentieren',
    'Ohne Vorher-Nachher-Maße ist ein Umbau schwer vergleichbar.',
    'Einfaches Werkzeug, aber für reproduzierbare Tests zentral.',
    '{"key":"measuring_tape_marker","name":"Maßband und Markierstift","toolType":"measurement","skillLevel":"beginner","usedFor":"Sitzbreite, Kanten, Schmerzpunkte und Änderungen dokumentieren","riskNotes":"Ohne Vorher-Nachher-Maße ist ein Umbau schwer vergleichbar.","buyingNotes":"Einfaches Werkzeug, aber für reproduzierbare Tests zentral."}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    tool_type = EXCLUDED.tool_type,
    skill_level = EXCLUDED.skill_level,
    used_for = EXCLUDED.used_for,
    risk_notes = EXCLUDED.risk_notes,
    buying_notes = EXCLUDED.buying_notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO workshop_tools (
    key, name, tool_type, skill_level, used_for, risk_notes, buying_notes, source_data, updated_at
  )
  VALUES (
    'heat_gun',
    'Heißluftföhn',
    'cover_work',
    'advanced',
    'Bezug vorsichtig anpassen und Falten reduzieren',
    'Überhitzung kann Bezug, Nähte oder Schaum zerstören.',
    'Nur mit Temperaturkontrolle und viel Abstand verwenden.',
    '{"key":"heat_gun","name":"Heißluftföhn","toolType":"cover_work","skillLevel":"advanced","usedFor":"Bezug vorsichtig anpassen und Falten reduzieren","riskNotes":"Überhitzung kann Bezug, Nähte oder Schaum zerstören.","buyingNotes":"Nur mit Temperaturkontrolle und viel Abstand verwenden."}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    tool_type = EXCLUDED.tool_type,
    skill_level = EXCLUDED.skill_level,
    used_for = EXCLUDED.used_for,
    risk_notes = EXCLUDED.risk_notes,
    buying_notes = EXCLUDED.buying_notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO buying_channels (
    key, name, channel_type, country_code, best_for, affiliate_potential,
    trust_level, notes, source_data, updated_at
  )
  VALUES (
    'suzuki_dealer_de',
    'Suzuki Vertragshändler',
    'oem_dealer',
    'de',
    'OEM Zubehör, Teilenummern, Passformklärung, Garantiefragen',
    'low',
    4,
    'Wichtig für Premium-Sitz und offizielle Zubehörteile.',
    '{"key":"suzuki_dealer_de","name":"Suzuki Vertragshändler","channelType":"oem_dealer","country":"DE","bestFor":"OEM Zubehör, Teilenummern, Passformklärung, Garantiefragen","affiliatePotential":"low","trustLevel":4,"notes":"Wichtig für Premium-Sitz und offizielle Zubehörteile."}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    channel_type = EXCLUDED.channel_type,
    country_code = EXCLUDED.country_code,
    best_for = EXCLUDED.best_for,
    affiliate_potential = EXCLUDED.affiliate_potential,
    trust_level = EXCLUDED.trust_level,
    notes = EXCLUDED.notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO buying_channels (
    key, name, channel_type, country_code, best_for, affiliate_potential,
    trust_level, notes, source_data, updated_at
  )
  VALUES (
    'amazon_de',
    'Amazon.de',
    'marketplace',
    'de',
    '3D-Mesh, einfache Auflagen, Werkzeug, schnelle Rückgabe',
    'high',
    3,
    'Gut für reversible Tests, aber Produktqualität stark prüfen.',
    '{"key":"amazon_de","name":"Amazon.de","channelType":"marketplace","country":"DE","bestFor":"3D-Mesh, einfache Auflagen, Werkzeug, schnelle Rückgabe","affiliatePotential":"high","trustLevel":3,"notes":"Gut für reversible Tests, aber Produktqualität stark prüfen."}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    channel_type = EXCLUDED.channel_type,
    country_code = EXCLUDED.country_code,
    best_for = EXCLUDED.best_for,
    affiliate_potential = EXCLUDED.affiliate_potential,
    trust_level = EXCLUDED.trust_level,
    notes = EXCLUDED.notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO buying_channels (
    key, name, channel_type, country_code, best_for, affiliate_potential,
    trust_level, notes, source_data, updated_at
  )
  VALUES (
    'louis_de',
    'Louis',
    'motorcycle_retailer',
    'de',
    'Motorradzubehör, Auflagen, Werkzeug, Filialberatung',
    'medium',
    4,
    'Relevanter deutscher Händler für spätere Produktkarten.',
    '{"key":"louis_de","name":"Louis","channelType":"motorcycle_retailer","country":"DE","bestFor":"Motorradzubehör, Auflagen, Werkzeug, Filialberatung","affiliatePotential":"medium","trustLevel":4,"notes":"Relevanter deutscher Händler für spätere Produktkarten."}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    channel_type = EXCLUDED.channel_type,
    country_code = EXCLUDED.country_code,
    best_for = EXCLUDED.best_for,
    affiliate_potential = EXCLUDED.affiliate_potential,
    trust_level = EXCLUDED.trust_level,
    notes = EXCLUDED.notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO buying_channels (
    key, name, channel_type, country_code, best_for, affiliate_potential,
    trust_level, notes, source_data, updated_at
  )
  VALUES (
    'polo_de',
    'Polo Motorrad',
    'motorcycle_retailer',
    'de',
    'Motorradzubehör, Werkzeug, Bekleidung und Komforttests',
    'medium',
    4,
    'Interessant für Preisvergleiche und stationären Kauf.',
    '{"key":"polo_de","name":"Polo Motorrad","channelType":"motorcycle_retailer","country":"DE","bestFor":"Motorradzubehör, Werkzeug, Bekleidung und Komforttests","affiliatePotential":"medium","trustLevel":4,"notes":"Interessant für Preisvergleiche und stationären Kauf."}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    channel_type = EXCLUDED.channel_type,
    country_code = EXCLUDED.country_code,
    best_for = EXCLUDED.best_for,
    affiliate_potential = EXCLUDED.affiliate_potential,
    trust_level = EXCLUDED.trust_level,
    notes = EXCLUDED.notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO buying_channels (
    key, name, channel_type, country_code, best_for, affiliate_potential,
    trust_level, notes, source_data, updated_at
  )
  VALUES (
    'local_upholsterer_de',
    'Lokaler Sitzbank-Sattler',
    'service_provider',
    'de',
    'individuelle Form, Schaumaufbau, Bezug, Sitzheizung',
    'service_directory',
    3,
    'Später als kuratiertes Verzeichnis mit Fotos, Regionen und Spezialisierung.',
    '{"key":"local_upholsterer_de","name":"Lokaler Sitzbank-Sattler","channelType":"service_provider","country":"DE","bestFor":"individuelle Form, Schaumaufbau, Bezug, Sitzheizung","affiliatePotential":"service_directory","trustLevel":3,"notes":"Später als kuratiertes Verzeichnis mit Fotos, Regionen und Spezialisierung."}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    channel_type = EXCLUDED.channel_type,
    country_code = EXCLUDED.country_code,
    best_for = EXCLUDED.best_for,
    affiliate_potential = EXCLUDED.affiliate_potential,
    trust_level = EXCLUDED.trust_level,
    notes = EXCLUDED.notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
DELETE FROM content_media_links;
INSERT INTO media_assets (
    key, title, description, local_path, download_url, source_page_url,
    source_name, creator, license_name, license_code, license_url, rights_status,
    attribution_required, share_alike_required, modification_allowed,
    commercial_use_allowed, endorsement_warning, credit_line, alt, caption,
    dominant_color, aspect_ratio, object_position, recommended_usage, notes,
    source_data, updated_at
  )
  VALUES (
    'motorcycle_seats_camden_commons',
    'Motorcycle seats at Camden Town',
    'General motorcycle seat and aftermarket seat visual for buying and category pages.',
    '/assets/media/m01-camden.jpg',
    'https://commons.wikimedia.org/wiki/Special:Redirect/file/Motorcycle_seats_at_Camden_Town_(6418524669).jpg',
    'https://commons.wikimedia.org/wiki/File:Motorcycle_seats_at_Camden_Town_(6418524669).jpg',
    'Wikimedia Commons',
    'Shadowgate',
    'Creative Commons Attribution 2.0 Generic',
    'CC BY 2.0',
    'https://creativecommons.org/licenses/by/2.0/',
    'usable_with_attribution',
    true,
    false,
    true,
    true,
    true,
    'Photo: Shadowgate, CC BY 2.0, via Wikimedia Commons',
    'Several motorcycle seats displayed at a market stall',
    'Aftermarket seats and used parts are useful for comparison, but fitment still needs model-year checks.',
    '#4b4037',
    '3 / 2',
    'center',
    '["card","section","buying"]'::jsonb,
    'Use with visible attribution on pages where the image appears.',
    '{"key":"motorcycle_seats_camden_commons","title":"Motorcycle seats at Camden Town","description":"General motorcycle seat and aftermarket seat visual for buying and category pages.","localPath":"/assets/media/m01-camden.jpg","downloadUrl":"https://commons.wikimedia.org/wiki/Special:Redirect/file/Motorcycle_seats_at_Camden_Town_(6418524669).jpg","sourcePageUrl":"https://commons.wikimedia.org/wiki/File:Motorcycle_seats_at_Camden_Town_(6418524669).jpg","sourceName":"Wikimedia Commons","creator":"Shadowgate","licenseName":"Creative Commons Attribution 2.0 Generic","licenseCode":"CC BY 2.0","licenseUrl":"https://creativecommons.org/licenses/by/2.0/","rightsStatus":"usable_with_attribution","attributionRequired":true,"shareAlikeRequired":false,"modificationAllowed":true,"commercialUseAllowed":true,"endorsementWarning":true,"creditLine":"Photo: Shadowgate, CC BY 2.0, via Wikimedia Commons","alt":"Several motorcycle seats displayed at a market stall","caption":"Aftermarket seats and used parts are useful for comparison, but fitment still needs model-year checks.","dominantColor":"#4b4037","aspectRatio":"3 / 2","objectPosition":"center","recommendedUsage":["card","section","buying"],"links":[{"entityType":"buying_channel","entityKey":"local_upholsterer_de","usage":"card","priority":1},{"entityType":"product_category","entityKey":"aftermarket_seat","usage":"card","priority":1}],"status":"active","notes":"Use with visible attribution on pages where the image appears."}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    local_path = EXCLUDED.local_path,
    download_url = EXCLUDED.download_url,
    source_page_url = EXCLUDED.source_page_url,
    source_name = EXCLUDED.source_name,
    creator = EXCLUDED.creator,
    license_name = EXCLUDED.license_name,
    license_code = EXCLUDED.license_code,
    license_url = EXCLUDED.license_url,
    rights_status = EXCLUDED.rights_status,
    attribution_required = EXCLUDED.attribution_required,
    share_alike_required = EXCLUDED.share_alike_required,
    modification_allowed = EXCLUDED.modification_allowed,
    commercial_use_allowed = EXCLUDED.commercial_use_allowed,
    endorsement_warning = EXCLUDED.endorsement_warning,
    credit_line = EXCLUDED.credit_line,
    alt = EXCLUDED.alt,
    caption = EXCLUDED.caption,
    dominant_color = EXCLUDED.dominant_color,
    aspect_ratio = EXCLUDED.aspect_ratio,
    object_position = EXCLUDED.object_position,
    recommended_usage = EXCLUDED.recommended_usage,
    notes = EXCLUDED.notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO content_media_links (
      media_key, entity_type, entity_key, usage, priority
    )
    VALUES (
      'motorcycle_seats_camden_commons',
      'buying_channel',
      'local_upholsterer_de',
      'card',
      1
    )
    ON CONFLICT (media_key, entity_type, entity_key, usage) DO UPDATE SET
      priority = EXCLUDED.priority;
INSERT INTO content_media_links (
      media_key, entity_type, entity_key, usage, priority
    )
    VALUES (
      'motorcycle_seats_camden_commons',
      'product_category',
      'aftermarket_seat',
      'card',
      1
    )
    ON CONFLICT (media_key, entity_type, entity_key, usage) DO UPDATE SET
      priority = EXCLUDED.priority;
INSERT INTO media_assets (
    key, title, description, local_path, download_url, source_page_url,
    source_name, creator, license_name, license_code, license_url, rights_status,
    attribution_required, share_alike_required, modification_allowed,
    commercial_use_allowed, endorsement_warning, credit_line, alt, caption,
    dominant_color, aspect_ratio, object_position, recommended_usage, notes,
    source_data, updated_at
  )
  VALUES (
    'touring_seat_goldwing_commons',
    'Honda Goldwing 1800 F6B detail',
    'Touring motorcycle seat detail for long-distance comfort context.',
    '/assets/media/m02-goldwing.jpg',
    'https://commons.wikimedia.org/wiki/Special:Redirect/file/Honda_Goldwing_1800_F6B_detail.jpg',
    'https://commons.wikimedia.org/wiki/File:Honda_Goldwing_1800_F6B_detail.jpg',
    'Wikimedia Commons',
    'Addvisor',
    'Creative Commons Attribution-ShareAlike 4.0 International',
    'CC BY-SA 4.0',
    'https://creativecommons.org/licenses/by-sa/4.0/',
    'usable_with_attribution_sharealike',
    true,
    true,
    true,
    true,
    true,
    'Photo: Addvisor, CC BY-SA 4.0, via Wikimedia Commons',
    'Large touring motorcycle seat detail on a Honda Goldwing',
    'Touring seats solve different problems than short city or sporty weekend seats.',
    '#202125',
    '4 / 3',
    'center',
    '["card","section","touring"]'::jsonb,
    'Avoid implying Honda, Addvisor, or Wikimedia endorse Moto Seat Lab.',
    '{"key":"touring_seat_goldwing_commons","title":"Honda Goldwing 1800 F6B detail","description":"Touring motorcycle seat detail for long-distance comfort context.","localPath":"/assets/media/m02-goldwing.jpg","downloadUrl":"https://commons.wikimedia.org/wiki/Special:Redirect/file/Honda_Goldwing_1800_F6B_detail.jpg","sourcePageUrl":"https://commons.wikimedia.org/wiki/File:Honda_Goldwing_1800_F6B_detail.jpg","sourceName":"Wikimedia Commons","creator":"Addvisor","licenseName":"Creative Commons Attribution-ShareAlike 4.0 International","licenseCode":"CC BY-SA 4.0","licenseUrl":"https://creativecommons.org/licenses/by-sa/4.0/","rightsStatus":"usable_with_attribution_sharealike","attributionRequired":true,"shareAlikeRequired":true,"modificationAllowed":true,"commercialUseAllowed":true,"endorsementWarning":true,"creditLine":"Photo: Addvisor, CC BY-SA 4.0, via Wikimedia Commons","alt":"Large touring motorcycle seat detail on a Honda Goldwing","caption":"Touring seats solve different problems than short city or sporty weekend seats.","dominantColor":"#202125","aspectRatio":"4 / 3","objectPosition":"center","recommendedUsage":["card","section","touring"],"links":[{"entityType":"motorcycle_profile","entityKey":"bmw-r-1300-gs","usage":"card","priority":3},{"entityType":"solution_path","entityKey":"upholsterer_rebuild","usage":"section","priority":2}],"status":"active","notes":"Avoid implying Honda, Addvisor, or Wikimedia endorse Moto Seat Lab."}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    local_path = EXCLUDED.local_path,
    download_url = EXCLUDED.download_url,
    source_page_url = EXCLUDED.source_page_url,
    source_name = EXCLUDED.source_name,
    creator = EXCLUDED.creator,
    license_name = EXCLUDED.license_name,
    license_code = EXCLUDED.license_code,
    license_url = EXCLUDED.license_url,
    rights_status = EXCLUDED.rights_status,
    attribution_required = EXCLUDED.attribution_required,
    share_alike_required = EXCLUDED.share_alike_required,
    modification_allowed = EXCLUDED.modification_allowed,
    commercial_use_allowed = EXCLUDED.commercial_use_allowed,
    endorsement_warning = EXCLUDED.endorsement_warning,
    credit_line = EXCLUDED.credit_line,
    alt = EXCLUDED.alt,
    caption = EXCLUDED.caption,
    dominant_color = EXCLUDED.dominant_color,
    aspect_ratio = EXCLUDED.aspect_ratio,
    object_position = EXCLUDED.object_position,
    recommended_usage = EXCLUDED.recommended_usage,
    notes = EXCLUDED.notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO content_media_links (
      media_key, entity_type, entity_key, usage, priority
    )
    VALUES (
      'touring_seat_goldwing_commons',
      'motorcycle_profile',
      'bmw-r-1300-gs',
      'card',
      3
    )
    ON CONFLICT (media_key, entity_type, entity_key, usage) DO UPDATE SET
      priority = EXCLUDED.priority;
INSERT INTO content_media_links (
      media_key, entity_type, entity_key, usage, priority
    )
    VALUES (
      'touring_seat_goldwing_commons',
      'solution_path',
      'upholsterer_rebuild',
      'section',
      2
    )
    ON CONFLICT (media_key, entity_type, entity_key, usage) DO UPDATE SET
      priority = EXCLUDED.priority;
INSERT INTO media_assets (
    key, title, description, local_path, download_url, source_page_url,
    source_name, creator, license_name, license_code, license_url, rights_status,
    attribution_required, share_alike_required, modification_allowed,
    commercial_use_allowed, endorsement_warning, credit_line, alt, caption,
    dominant_color, aspect_ratio, object_position, recommended_usage, notes,
    source_data, updated_at
  )
  VALUES (
    'leather_sample_commons',
    'Leather material sample',
    'Leather and upholstery material texture for seat-cover discussions.',
    '/assets/media/m03-leather.jpg',
    'https://commons.wikimedia.org/wiki/Special:Redirect/file/Cuero_Muestra_material.JPG',
    'https://commons.wikimedia.org/wiki/File:Cuero_Muestra_material.JPG',
    'Wikimedia Commons',
    'Imapar Ltda',
    'Creative Commons Attribution-ShareAlike 3.0 Unported',
    'CC BY-SA 3.0',
    'https://creativecommons.org/licenses/by-sa/3.0/',
    'usable_with_attribution_sharealike',
    true,
    true,
    true,
    true,
    true,
    'Photo: Imapar Ltda, CC BY-SA 3.0, via Wikimedia Commons',
    'Close-up sample of leather upholstery material',
    'Cover material affects grip, water behavior, cleaning and heat feeling.',
    '#6f4f3c',
    '4 / 3',
    'center',
    '["card","material","section"]'::jsonb,
    'Use as generic material texture, not as a specific motorcycle-seat cover product.',
    '{"key":"leather_sample_commons","title":"Leather material sample","description":"Leather and upholstery material texture for seat-cover discussions.","localPath":"/assets/media/m03-leather.jpg","downloadUrl":"https://commons.wikimedia.org/wiki/Special:Redirect/file/Cuero_Muestra_material.JPG","sourcePageUrl":"https://commons.wikimedia.org/wiki/File:Cuero_Muestra_material.JPG","sourceName":"Wikimedia Commons","creator":"Imapar Ltda","licenseName":"Creative Commons Attribution-ShareAlike 3.0 Unported","licenseCode":"CC BY-SA 3.0","licenseUrl":"https://creativecommons.org/licenses/by-sa/3.0/","rightsStatus":"usable_with_attribution_sharealike","attributionRequired":true,"shareAlikeRequired":true,"modificationAllowed":true,"commercialUseAllowed":true,"endorsementWarning":true,"creditLine":"Photo: Imapar Ltda, CC BY-SA 3.0, via Wikimedia Commons","alt":"Close-up sample of leather upholstery material","caption":"Cover material affects grip, water behavior, cleaning and heat feeling.","dominantColor":"#6f4f3c","aspectRatio":"4 / 3","objectPosition":"center","recommendedUsage":["card","material","section"],"links":[{"entityType":"seat_material","entityKey":"anti_slip_cover","usage":"card","priority":1}],"status":"active","notes":"Use as generic material texture, not as a specific motorcycle-seat cover product."}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    local_path = EXCLUDED.local_path,
    download_url = EXCLUDED.download_url,
    source_page_url = EXCLUDED.source_page_url,
    source_name = EXCLUDED.source_name,
    creator = EXCLUDED.creator,
    license_name = EXCLUDED.license_name,
    license_code = EXCLUDED.license_code,
    license_url = EXCLUDED.license_url,
    rights_status = EXCLUDED.rights_status,
    attribution_required = EXCLUDED.attribution_required,
    share_alike_required = EXCLUDED.share_alike_required,
    modification_allowed = EXCLUDED.modification_allowed,
    commercial_use_allowed = EXCLUDED.commercial_use_allowed,
    endorsement_warning = EXCLUDED.endorsement_warning,
    credit_line = EXCLUDED.credit_line,
    alt = EXCLUDED.alt,
    caption = EXCLUDED.caption,
    dominant_color = EXCLUDED.dominant_color,
    aspect_ratio = EXCLUDED.aspect_ratio,
    object_position = EXCLUDED.object_position,
    recommended_usage = EXCLUDED.recommended_usage,
    notes = EXCLUDED.notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO content_media_links (
      media_key, entity_type, entity_key, usage, priority
    )
    VALUES (
      'leather_sample_commons',
      'seat_material',
      'anti_slip_cover',
      'card',
      1
    )
    ON CONFLICT (media_key, entity_type, entity_key, usage) DO UPDATE SET
      priority = EXCLUDED.priority;
INSERT INTO media_assets (
    key, title, description, local_path, download_url, source_page_url,
    source_name, creator, license_name, license_code, license_url, rights_status,
    attribution_required, share_alike_required, modification_allowed,
    commercial_use_allowed, endorsement_warning, credit_line, alt, caption,
    dominant_color, aspect_ratio, object_position, recommended_usage, notes,
    source_data, updated_at
  )
  VALUES (
    'pexels_forest_curve_motorcyclist',
    'Motorcyclist on curved forest road',
    'Atmospheric riding image for touring and country-road context.',
    '/assets/media/m04-curve.jpg',
    'https://images.pexels.com/photos/31621763/pexels-photo-31621763.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://www.pexels.com/photo/motorcyclist-on-curved-road-in-forest-setting-31621763/',
    'Pexels',
    'Tiwi Riders',
    'Pexels License',
    'PEXELS',
    'https://www.pexels.com/license/',
    'usable_without_required_attribution',
    false,
    false,
    true,
    true,
    true,
    'Photo: Tiwi Riders / Pexels',
    'Motorcyclist riding through a curve on a forest road',
    'Country-road posture, wind pressure and seat angle change the comfort problem.',
    '#26352f',
    '16 / 9',
    'center',
    '["hero","section","touring"]'::jsonb,
    'Attribution is not required by Pexels, but the credit line can be shown in an asset register.',
    '{"key":"pexels_forest_curve_motorcyclist","title":"Motorcyclist on curved forest road","description":"Atmospheric riding image for touring and country-road context.","localPath":"/assets/media/m04-curve.jpg","downloadUrl":"https://images.pexels.com/photos/31621763/pexels-photo-31621763.jpeg?auto=compress&cs=tinysrgb&w=1600","sourcePageUrl":"https://www.pexels.com/photo/motorcyclist-on-curved-road-in-forest-setting-31621763/","sourceName":"Pexels","creator":"Tiwi Riders","licenseName":"Pexels License","licenseCode":"PEXELS","licenseUrl":"https://www.pexels.com/license/","rightsStatus":"usable_without_required_attribution","attributionRequired":false,"shareAlikeRequired":false,"modificationAllowed":true,"commercialUseAllowed":true,"endorsementWarning":true,"creditLine":"Photo: Tiwi Riders / Pexels","alt":"Motorcyclist riding through a curve on a forest road","caption":"Country-road posture, wind pressure and seat angle change the comfort problem.","dominantColor":"#26352f","aspectRatio":"16 / 9","objectPosition":"center","recommendedUsage":["hero","section","touring"],"links":[{"entityType":"motorcycle_profile","entityKey":"suzuki-gsx-s1000gx","usage":"hero","priority":2}],"status":"active","notes":"Attribution is not required by Pexels, but the credit line can be shown in an asset register."}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    local_path = EXCLUDED.local_path,
    download_url = EXCLUDED.download_url,
    source_page_url = EXCLUDED.source_page_url,
    source_name = EXCLUDED.source_name,
    creator = EXCLUDED.creator,
    license_name = EXCLUDED.license_name,
    license_code = EXCLUDED.license_code,
    license_url = EXCLUDED.license_url,
    rights_status = EXCLUDED.rights_status,
    attribution_required = EXCLUDED.attribution_required,
    share_alike_required = EXCLUDED.share_alike_required,
    modification_allowed = EXCLUDED.modification_allowed,
    commercial_use_allowed = EXCLUDED.commercial_use_allowed,
    endorsement_warning = EXCLUDED.endorsement_warning,
    credit_line = EXCLUDED.credit_line,
    alt = EXCLUDED.alt,
    caption = EXCLUDED.caption,
    dominant_color = EXCLUDED.dominant_color,
    aspect_ratio = EXCLUDED.aspect_ratio,
    object_position = EXCLUDED.object_position,
    recommended_usage = EXCLUDED.recommended_usage,
    notes = EXCLUDED.notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO content_media_links (
      media_key, entity_type, entity_key, usage, priority
    )
    VALUES (
      'pexels_forest_curve_motorcyclist',
      'motorcycle_profile',
      'suzuki-gsx-s1000gx',
      'hero',
      2
    )
    ON CONFLICT (media_key, entity_type, entity_key, usage) DO UPDATE SET
      priority = EXCLUDED.priority;
INSERT INTO media_assets (
    key, title, description, local_path, download_url, source_page_url,
    source_name, creator, license_name, license_code, license_url, rights_status,
    attribution_required, share_alike_required, modification_allowed,
    commercial_use_allowed, endorsement_warning, credit_line, alt, caption,
    dominant_color, aspect_ratio, object_position, recommended_usage, notes,
    source_data, updated_at
  )
  VALUES (
    'unsplash_touring_motorcycle_road',
    'Touring motorcycle beside farm road',
    'Road-trip motorcycle image for long-distance and travel context.',
    '/assets/media/m05-road.jpg',
    'https://unsplash.com/photos/sFiNwoqjwrI/download?force=true&w=1600',
    'https://unsplash.com/photos/touring-motorcycle-beside-farm-road-sFiNwoqjwrI',
    'Unsplash',
    'Donald Giannatti',
    'Unsplash License',
    'UNSPLASH',
    'https://unsplash.com/license',
    'usable_without_required_attribution',
    false,
    false,
    true,
    true,
    true,
    'Photo: Donald Giannatti / Unsplash',
    'Touring motorcycle parked beside an open road',
    'Long rides need a different seat decision than short commutes.',
    '#8d8170',
    '16 / 9',
    'center',
    '["hero","section","touring"]'::jsonb,
    'Do not use in a way that implies the photographer endorses the site.',
    '{"key":"unsplash_touring_motorcycle_road","title":"Touring motorcycle beside farm road","description":"Road-trip motorcycle image for long-distance and travel context.","localPath":"/assets/media/m05-road.jpg","downloadUrl":"https://unsplash.com/photos/sFiNwoqjwrI/download?force=true&w=1600","sourcePageUrl":"https://unsplash.com/photos/touring-motorcycle-beside-farm-road-sFiNwoqjwrI","sourceName":"Unsplash","creator":"Donald Giannatti","licenseName":"Unsplash License","licenseCode":"UNSPLASH","licenseUrl":"https://unsplash.com/license","rightsStatus":"usable_without_required_attribution","attributionRequired":false,"shareAlikeRequired":false,"modificationAllowed":true,"commercialUseAllowed":true,"endorsementWarning":true,"creditLine":"Photo: Donald Giannatti / Unsplash","alt":"Touring motorcycle parked beside an open road","caption":"Long rides need a different seat decision than short commutes.","dominantColor":"#8d8170","aspectRatio":"16 / 9","objectPosition":"center","recommendedUsage":["hero","section","touring"],"links":[{"entityType":"solution_path","entityKey":"premium_touring_seat","usage":"section","priority":2}],"status":"active","notes":"Do not use in a way that implies the photographer endorses the site."}'::jsonb,
    now()
  )
  ON CONFLICT (key) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    local_path = EXCLUDED.local_path,
    download_url = EXCLUDED.download_url,
    source_page_url = EXCLUDED.source_page_url,
    source_name = EXCLUDED.source_name,
    creator = EXCLUDED.creator,
    license_name = EXCLUDED.license_name,
    license_code = EXCLUDED.license_code,
    license_url = EXCLUDED.license_url,
    rights_status = EXCLUDED.rights_status,
    attribution_required = EXCLUDED.attribution_required,
    share_alike_required = EXCLUDED.share_alike_required,
    modification_allowed = EXCLUDED.modification_allowed,
    commercial_use_allowed = EXCLUDED.commercial_use_allowed,
    endorsement_warning = EXCLUDED.endorsement_warning,
    credit_line = EXCLUDED.credit_line,
    alt = EXCLUDED.alt,
    caption = EXCLUDED.caption,
    dominant_color = EXCLUDED.dominant_color,
    aspect_ratio = EXCLUDED.aspect_ratio,
    object_position = EXCLUDED.object_position,
    recommended_usage = EXCLUDED.recommended_usage,
    notes = EXCLUDED.notes,
    source_data = EXCLUDED.source_data,
    updated_at = now();
INSERT INTO content_media_links (
      media_key, entity_type, entity_key, usage, priority
    )
    VALUES (
      'unsplash_touring_motorcycle_road',
      'solution_path',
      'premium_touring_seat',
      'section',
      2
    )
    ON CONFLICT (media_key, entity_type, entity_key, usage) DO UPDATE SET
      priority = EXCLUDED.priority;
INSERT INTO import_runs (label, row_counts)
VALUES ('json seed import', '{"countries":1,"motorcycles":9,"solution_paths":5,"product_categories":6,"seat_options":4,"research_sources":3,"technical_profiles":5,"seat_materials":6,"workshop_tools":6,"buying_channels":5,"media_assets":5,"content_media_links":7}'::jsonb);
COMMIT;
